#!/usr/bin/env python
# -*- coding: utf-8 -*-

# A metaprogramming script that consumes json5 files to produce c source files
# and c header files for atomtree, usually specifically for ATUI.
# see atomtree/atui_tables/README.md for more info on what the inputs are about
# see also atomtree/atui/atui.h and atomtree/atui/ppatui.h

# To generate C source files branches:
# ppatui.py -s -o output.c -i input.json5
# Produce header files of the generated functions:
# ppatui.py -d -o output.h -i input.json5

# To generate header files for the enums:
# ppatui.py -d -o output.h -i input.json5

import sys
import copy
import json5
import pathlib
import argparse
from typing import Callable

def pcilut_to_c(
		atui_data:dict,
		fname:str
		) -> str:
	# see atomtree/pci_id_lut.h
	assert (atui_data["class"] == "pci_id_lut"), fname

	unique_ids:set = set()
	card:dict
	for card in atui_data["ids"]:
		part_id:int = ((card["vendor"]<<16) | card["device"])
		# we really shouldn't have two identical cards
		assert (part_id not in unique_ids), part_id
		unique_ids.add(part_id)
	del unique_ids
	pci_id_sorter:function = lambda card: ((card["vendor"]<<16)|card["device"])
	atui_data["ids"].sort(key=pci_id_sorter)

	cfile_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#include "standard.h"
#include "pci_id_lut.h"

struct atomtree_pci_id const %s[%u] = {
%s\
};
static_assert(%u < INT16_MAX); // reserve sign as flag for register_set_bsearch
"""
	entry_template:str = """\
	{
		.ids.vendor = 0x%04X, .ids.device = 0x%04X, .chip = %s,
%s\
	},
"""
	feature_flags:dict = {
		"MOBILITY":     "\t\t.flags.mobility = true,\n",
		"APU":          "\t\t.flags.APU = true,\n",
		"ACPI_ATPX":    "\t\t.flags.ACPI_ATPX = true,\n",
		"EXPERIMENTAL": "\t\t.flags.experimental_hw = true,\n",
		"SINGLE_CRTC":  "\t\t.flags.single_CRTC = true,\n",
		"AGP":          "\t\t.flags.AGP = true,\n",
		"IGPGART":      "\t\t.flags.igpgart = true,\n",
		"PCIe":         "\t\t.flags.PCIe = true,\n",
		"NEW_MEMMAP":   "\t\t.flags.new_memmap = true,\n",
		"PCI":          "\t\t.flags.PCI = true,\n",
	}
	entries_text:str = ""
	card:dict
	for card in atui_data["ids"]:
		flags_text:str = ""
		if "flags" in card:
			flag:str
			for flag in card["flags"]:
				flags_text += feature_flags[flag]
		entries_text += entry_template % (
			card["vendor"], card["device"], card["chip"],
			flags_text
		)
	out_text:str = cfile_header % (
		fname.lower(), len(atui_data["ids"]),
		entries_text,
		len(atui_data["ids"]),
	)
	return out_text
def pcilut_to_h(
		atui_data:dict,
		fname:str
		) -> str:
	assert (atui_data["class"] == "pci_id_lut"), fname
	header_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#ifndef %s_H
#define %s_H
extern struct atomtree_pci_id const %s[%u];
#endif
"""
	out_text:str = header_header % (
		fname.upper(), fname.upper(),
		fname.lower(), len(atui_data["ids"]),
	)
	return out_text


def description_to_text(
		description:dict,
		indent:str
		) -> str:
	# language codes follow ISO 639-3
	# description segment meant for a segment of a c file
	#indended to be used like
	# ".description = {%s}" % description_to_text(...)
	if (description is None):
		return ""
	lang_type:str = ""
	languages:tuple = ("eng",)
	descriptions:list = [None,] * len(languages)
	descr_index:int = 0
	trans:dict 
	for trans in description:
		descr_index:int = languages.index(trans)
		descriptions[descr_index]:str = description[trans]
 
	child_indent:str = indent + "\t"
	descr_template:str = "\n%s" + indent

	des_entry_template:str = child_indent + "\"%s\",\n"
	des_null_entry_template:str = child_indent + "NULL,\n"

	descr_texts:str = ""
	d:str
	for d in descriptions:
		if d:
			descr_texts += des_entry_template % d.replace("\"","\\\"")
		else:
			descr_texts += des_null_entry_template
	return descr_template % descr_texts


def searchfield_to_h(
		atui_data:dict,
		fname:str
		) -> str:
	assert(atui_data["class"] == "searchfield"), fname
	header_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#ifndef %s_H
#define %s_H

"""
	field_template:str = "extern struct register_set const %s_reg_set;\n"
	header_end:str = "\n#endif\n"
	out_text:str = header_header % (fname.upper(), fname.upper())
	field:dict
	for field in atui_data["fields"]:
		out_text += field_template % field["name"]
	return out_text + header_end
def searchfield_to_c(
		atui_data:dict,
		fname:str
		) -> str:
	assert(atui_data["class"] == "searchfield"), fname
	cfile_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#include "standard.h"
#include "atomtree.h"
#include "atui.h"
#include "atui_allocator.h"

"""
	field_template:str = """\
struct register_set const %s_reg_set = {
	.num_reg_set_addresses = %u,
	.set_name = "%s",
	.entries = {
%s\
	},
};
static_assert(%u < INT16_MAX); // reserve sign as flag for register_set_bsearch

"""
	field_entry:str = """\
		{
			.address = %s,
			.index_name = "%s",
			.field_name = "%s",
			.atui_branch_func = _atui_%s,
		},
"""
	out_text:str = cfile_header
	entry_text:str = ""
	num_constants:int = 0
	field:dict
	for field in atui_data["fields"]:
		entry_text:str = ""
		entry:dict
		for entry in field["registers"]:
			index_name:str = entry["index"]
			field_name:str = entry["field"]
			entry_text += field_entry % (
				index_name, index_name,  field_name, field_name
			)
		num_constants:int = len(field["registers"])
		out_text += field_template % (
			field["name"],
			num_constants, field["name"],
			entry_text,
			num_constants, # assert
		)
	return out_text


def array_to_h(
		atui_data:dict,
		fname:str
		) -> str:
	assert (atui_data["class"] == "array"), fname
	header_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#ifndef %s_H
#define %s_H

"""
	array_template:str = "extern %s const %s[%u];\n"
	header_end:str = "\n#endif\n"
	out_text:str = header_header % (fname.upper(), fname.upper())
	array:dict
	for array in atui_data["arrays"]:
		out_text += array_template % (
			array["type"], array["name"], len(array["constants"])
		)
	return out_text + header_end
def array_to_c(
		atui_data:dict,
		fname:str
		) -> str:
	assert (atui_data["class"] == "array"), fname
	cfile_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#include "standard.h"
#include "atomtree.h"

"""
	array_template = """\
%s const %s[%u] = {
%s\
};

"""
	array_entry:str = "\t%s,\n"
	out_text:str = cfile_header
	entry_text:str = ""
	array:dict
	for array in atui_data["arrays"]:
		entry_text:str = ""
		entry:dict
		for entry in array["constants"]:
			entry_text += array_entry % entry
		out_text += array_template % (
			array["type"], array["name"], len(array["constants"]),
			entry_text
		)
	return out_text


def enum_to_h(
		atui_data:dict,
		fname:str
		) -> str:
	assert (atui_data["class"] == "enum"), fname
	header_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#ifndef %s_H
#define %s_H

extern struct atui_enum const _atui_enumarray[%u];

"""
	enumarray_indicies_set_template:str = """\
enum enumarray_indicies_set {
%s\
	ATUI_ENUM_ARRAY_LENGTH
};
"""
	enum_index_entry_template:str = "\tATUI_ENUM_INDEX(%s) = %u,\n"
	enum_infer_template:str = """
// cannot be used with non-enums types
#define ATUI_ENUM_INFER(var) _Generic((var),\\
%s\
	default: NULL\\
)
"""
	enum_infer_entry_template:str = "\tenum %s: & ATUI_ENUM(%s),\\\n"
	enum_indexof_template:str = """
// cannot be used with non-enums types
#define ATUI_ENUM_INDEXOF(var) _Generic((var),\\
%s\
	default: ATUI_ENUM_ARRAY_LENGTH\\
)
"""
	enum_indexof_entry_template:str = "\tenum %s: ATUI_ENUM_INDEX(%s),\\\n"
	header_end:str = "\n#endif\n"

	enums:list = atui_data["enums"]
	num_enums:int = len(enums)

	i:int = 0
	indicies:str = ""
	infers:str = ""
	indexofs:str = ""
	while i < num_enums:
		enum:dict = enums[i]
		enum_name:str = enum["name"]
		indicies += enum_index_entry_template % (enum_name, i)
		infers += enum_infer_entry_template % (enum_name, enum_name)
		indexofs +=  enum_indexof_entry_template % (enum_name, enum_name)
		if "aliases" in enum:
			alias:str
			for alias in enum["aliases"]:
				indicies += enum_index_entry_template % (alias, i)
				infers += enum_infer_entry_template % (alias, alias)
				indexofs +=  enum_indexof_entry_template % (alias, alias)
		i += 1

	out_text = (
		header_header % (fname.upper(), fname.upper(), num_enums)
		+ enumarray_indicies_set_template % indicies
		+ enum_infer_template % infers
		+ enum_indexof_template % indexofs
		+ header_end
	)
	return out_text

def enum_to_c(
		atui_data:dict,
		fname:str
		) -> str:
	assert (atui_data["class"] == "enum"), fname
	cfile_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#include "standard.h"
#include "atomtree.h"
#include "atui.h"
#include "atui_allocator.h"

"""
	enumarray_template:str = """\
struct atui_enum const _atui_enumarray[%u] = {
%s\
};

"""
	enum_template:str = """\
	{
		.name_length = %u,
		.name = "%s",
		.num_entries = %u,
		.description = {%s},
		.enum_array = (struct atui_enum_entry const[%u]) {
%s\
		},
	},
"""
	enum_entry_template:str = """\
			{
				.name = \"%s\",
				.val = %s,
				.name_length = %u,
				.description = {%s},
			},
"""
	enum_entry_assert_template:str = """\
"""
	enum_assert_template:str = """\
static_assert(UINT8_MAX >= ATUI_ENUM(%s).num_entries);
"""

	# main meat
	enum_sets:str = "" # _atui_enumarray members
	enum_entries:str = "" #  struct atui_enum_entry
	entry_name:str = ""
	descr_text:str = ""
	enum:dict
	for enum in atui_data["enums"]:
		enum_entries:str = ""
		enum_entries_asserts:str = ""
		entry:dict
		for entry in enum["constants"]:
			entry_name:str = entry["name"]
			#out_text += enum_entry_assert_template % entry_name
			if "description" in entry:
				descr_text:str = description_to_text(
					entry["description"], "\t\t\t\t"
				)
			else:
				descr_text:str = ""
			enum_entries += enum_entry_template % (
				entry_name, entry_name, len(entry_name), descr_text
			)

		if "description" in enum:
			descr_text:str = description_to_text(enum["description"], "\t\t")
		else:
			descr_text:str = ""
		enum_sets += enum_template % (
			len(enum["name"]), enum["name"], len(enum["constants"]),
			descr_text,
			len(enum["constants"]),
			enum_entries
		)

	#asserts
	enum_asserts:str = ""
	enum_entries_asserts:str = ""
	#for enum in atui_data["enums"]:
	#	enum_asserts += enum_assert_template % enum["name"]

	out_text:str = (
		cfile_header
		+ enumarray_template % (len(atui_data["enums"]), enum_sets)
		+ enum_asserts
	)
	return out_text



class atui_type:
	# atomtree/atui/atui.h has a copy

	# fancy
	ATUI_NOFANCY:int   = 0
	ATUI_BITFIELD:int  = 1
	ATUI_STRING:int    = 2
	ATUI_ARRAY:int     = 3
	ATUI_GRAFT:int     = 4
	ATUI_SHOOT:int     = 5
	ATUI_PETIOLE:int   = 6
	ATUI_DYNARRAY:int  = 7
	_ATUI_BITCHILD:int = 8
	ATUI_TYPE_FANCY:tuple = (
		"ATUI_NOFANCY",
		"ATUI_BITFIELD",
		"ATUI_STRING",
		"ATUI_ARRAY",
		"ATUI_GRAFT",
		"ATUI_SHOOT",
		"ATUI_PETIOLE",
		"ATUI_DYNARRAY",
		"_ATUI_BITCHILD",
	)
	FANCIES_THAT_TAKE_RADIX:tuple = (
		ATUI_NOFANCY, ATUI_BITFIELD, ATUI_ARRAY, _ATUI_BITCHILD
	)
	FANCIES_THAT_TAKE_FANCYDATA:tuple = (
		ATUI_BITFIELD, ATUI_GRAFT, ATUI_SHOOT, ATUI_PETIOLE, ATUI_DYNARRAY
	)
	FANCIES_THAT_TAKE_ENUM:tuple = (
		ATUI_NOFANCY, ATUI_BITFIELD, _ATUI_BITCHILD,
	)
	FANCIES_THAT_TAKE_A_BRANCH:tuple = (ATUI_GRAFT, ATUI_SHOOT)

	# radix
	ATUI_NAN:int = 0x0
	ATUI_DEC:int = 0x1
	ATUI_HEX:int = 0x2
	ATUI_OCT:int = 0x3
	ATUI_BIN:int = 0x4
	ATUI_ANY:int = 0x7
	ATUI_TYPE_RADIX:tuple = (
		"ATUI_NAN",
		"ATUI_DEC",
		"ATUI_HEX",
		"ATUI_OCT",
		"ATUI_BIN",
	)

	# disable
	ATUI_DISPLAY:int   = 0
	ATUI_SUBONLY:int   = 1
	ATUI_NODISPLAY:int = 2
	ATUI_TYPE_DISABLE:tuple = (
		"ATUI_DISPLAY",
		"ATUI_SUBONLY",
		"ATUI_NODISPLAY",
	)

	fancy:int = None
	radix:int = None
	disable:int = None
	# signed ~ enum may be handled through C generics so usually False
	signed_num:bool = None
	fraction:bool = None
	has_enum:bool = None

class atui_leaf:
	# the python atui_leaf/atui_branch employs nonbinary logic where None is
	# unknown
	parent_is_leaf:bool = None # parent type; meta

	type:atui_type = None

	access:str = None # var
	access_meta:str  = None# for c preprocessor stuff
	name:str = None
	fancy_data = None #dict, str, list, atui_branch
	description:dict = None
	enum:str = None
	union:str = None # bitfield type

	def copy(self):
		return copy.deepcopy(self)

	def __init__(self,
			leaf:dict,
			defaults:dict,
			leaf_default:dict
			):
		self.parent_is_leaf = leaf_default["parent_is_leaf"]

		if "access" in leaf:
			self.access = leaf["access"]
			self.access_meta = leaf["access"]
		else:
			if "access" in leaf_default:
				self.access = leaf_default["access"]
				self.access_meta = leaf_default["access"]
			if "access_meta" in leaf_default:
				self.access_meta = leaf_default["access_meta"]

		if "name" in leaf:
			self.name = leaf["name"]
		elif "name" in leaf_default:
			self.name = leaf_default["name"]

		# have __expand_leaf_type  after name/access for easier debugging
		self.__expand_leaf_type(leaf, leaf_default)

		if self.type.fancy in atui_type.FANCIES_THAT_TAKE_FANCYDATA:
			if "fancy_data" in leaf:
				self.fancy_data = leaf["fancy_data"]
			else:
				self.fancy_data = leaf_default["fancy_data"]

		if "description" in leaf:
			self.description = leaf["description"]
		elif "description" in leaf_default:
			self.description = leaf_default["description"]

		if "enum" in leaf:
			self.enum = leaf["enum"]
		elif "enum" in leaf_default:
			self.enum = leaf_default["enum"]

		if "union" in leaf:
			self.union = leaf["union"]
		elif "union" in leaf_default:
			self.union = leaf_default["union"]

		self.__expand_leaf_fancy(defaults, leaf_default)

		assert(None is not self.name), (
			self.access, self.fancy_data,
			atui_type.ATUI_TYPE_FANCY[self.type.fancy],
			atui_type.ATUI_TYPE_RADIX[self.type.radix],
			atui_type.ATUI_TYPE_DISABLE[self.type.disable]
		)

	def __expand_leaf_type(self,
			leaf:dict,
			leaf_default:dict
			):
		self.type:atui_type = atui_type()

		fancy:str
		if "fancy" in leaf:
			fancy = leaf["fancy"]
		else:
			fancy = leaf_default["fancy"]
		assert (fancy in atui_type.ATUI_TYPE_FANCY), (self.name, fancy)
		self.type.fancy = atui_type.ATUI_TYPE_FANCY.index(fancy)

		display = None
		if "display" in leaf:
			display = leaf["display"]
		else:
			display = leaf_default["display"]
		if type(display) is str:
			if display in atui_type.ATUI_TYPE_RADIX:
				self.type.radix = atui_type.ATUI_TYPE_RADIX.index(display)
				self.type.disable = atui_type.ATUI_DISPLAY
			elif display in atui_type.ATUI_TYPE_DISABLE:
				self.type.radix = atui_type.ATUI_NAN
				self.type.disable = atui_type.ATUI_TYPE_DISABLE.index(display)
			else:
				assert(0), (self.name, display)
		elif type(display) is list:
			assert(self.type.fancy in atui_type.FANCIES_THAT_TAKE_RADIX), (
				self.name, fancy, display
			)
			if "ATUI_SIGNED" in display:
				self.type.signed_num = True
			if "ATUI_ENUM" in display:
				self.type.has_enum = True
			radix:str = None
			disable:str = None
			for flag in display:
				if flag in atui_type.ATUI_TYPE_RADIX:
					radix = flag
				elif flag in atui_type.ATUI_TYPE_DISABLE:
					disable = flag
			assert(radix in atui_type.ATUI_TYPE_RADIX), (self.name, radix)
			self.type.radix = atui_type.ATUI_TYPE_RADIX.index(radix)
			if disable:
				assert(disable in atui_type.ATUI_TYPE_DISABLE), self.name
				self.type.disable = atui_type.ATUI_TYPE_DISABLE.index(disable)
			else:
				self.type.disable = atui_type.ATUI_DISPLAY
		else:
			assert(0), self.name
		assert(None is not self.type.disable), self.name 
		if (self.type.has_enum
				and (self.type.fancy not in atui_type.FANCIES_THAT_TAKE_ENUM)
				):
			assert (0), "%s can't have an enum: %s" % (
				atui_type.ATUI_TYPE_FANCY[self.type.fancy], self.name
			)
			
	def __expand_leaf_fancy(self,
			defaults:dict,
			leaf_default:dict
			):
		match (self.type.fancy):
			case atui_type.ATUI_BITFIELD:
				if ("union" not in self.fancy_data):
					self.fancy_data["union"] = "typeof(*bios)"

				bitchild_default:dict = (
					defaults["leaf_defaults"]["bitchild"].copy()
				)
				# parent_is_leaf and _ATUI_BITCHILD should be set automatically
				# by branches_populate_defaults
				bitchild_default["access_meta"] = self.access_meta # c generics
				bitchild_default["union"] = self.fancy_data["union"]
				fields:list = []
				l:dict
				for l in self.fancy_data["fields"]:
					 fields.append(atui_leaf(l, defaults, bitchild_default))
				self.fancy_data["fields"] = fields

			case atui_type._ATUI_BITCHILD:
				if None is self.name:
					self.name = self.access
				# bitchild access_meta is incomplete; take parent/bitfield's
				self.access_meta = leaf_default["access_meta"]

			case atui_type.ATUI_ARRAY:
				self.access_meta += "[0]"

			case atui_type.ATUI_PETIOLE:
				self.fancy_data = atui_branch(
					{
						"c_type": "atui_nullstruct", # query after atui'ifying
						"name": self.name,
						"description": self.description,
						"table_start": "NULL", "table_size": "0",
						# start and size is handled by C-side branch allocator.
						"leaves": self.fancy_data
					},
					defaults, True
				)

				if (1 == len(self.fancy_data.leaves)):
					# copy c_struct of subleaf
					c_type:str = None
					subleaf:atui_leaf = self.fancy_data.leaves[0]
					match (subleaf.type.fancy):
						case atui_type.ATUI_BITFIELD:
							if "union" in subleaf.fancy_data:
								c_type = subleaf.fancy_data["union"]
							else:
								c_type = parent_branch.c_type
						case atui_type.ATUI_GRAFT | atui_type.ATUI_SHOOT:
							c_type = subleaf.facy_data[len("_atui_"):]
						case atui_type.ATUI_DYNARRAY:
							pattern = subleaf.fancy_data["pattern"]
							if ((1 == len(pattern))
									and (pattern[0].type.fancy
										in atui_type.FANCIES_THAT_TAKE_A_BRANCH
									)):
								c_type = pattern[0].fancy_data[len("_atui_"):]
						case _:
							pass
					if c_type:
						self.fancy_data.c_type = c_type

			case atui_type.ATUI_DYNARRAY:
				access_meta:str
				if self.access and ("NULL" != self.access):
					access_meta = self.access_meta # direct array
				else: # array of pointers
					self.access_meta = self.fancy_data["deferred"] + "[0]"
					self.access = None
					access_meta = self.fancy_data["deferred"]
				access_meta += "[0]" # c preprocessor stuff

				dynpattern_default:dict = (
					defaults["leaf_defaults"]["dynpattern"].copy()
				)
				dynpattern_default["access_meta"] = access_meta
				# parent_is_leaf should be set automatically by
				# branches_populate_defaults
				pattern:list = []
				l:dict
				for l in self.fancy_data["pattern"]:
					 pattern.append(atui_leaf(l, defaults, dynpattern_default))
				self.fancy_data["pattern"] = pattern

				if not ("enum" in self.fancy_data):
					self.fancy_data["enum"] = "NULL"

class atui_branch:
	# the python atui_leaf/atui_branch employs ternary logic: true/false/unknown
	# None is unknown
	c_prefix:str
	c_type:str
	name:str
	atomtree:str
	description:dict
	table_start:str
	table_size:str
	expanded:bool
	leaves:list

	def copy(self):
		return copy.deepcopy(self)

	def __init__(self,
			branch:dict,
			defaults:dict,
			populate_leaves:bool=True
			):
		branch_default:dict = defaults["branch_default"]
		if "c_prefix" in branch:
			self.c_prefix = branch["c_prefix"]
		else:
			self.c_prefix = branch_default["c_prefix"]

		if "c_type" in branch:
			self.c_type = branch["c_type"]
		else:
			self.c_type = branch_default["c_type"]

		if "atomtree" in branch:
			self.atomtree = branch["atomtree"]
		elif "atomtree" in branch_default:
			self.atomtree = branch_default["atomtree"]
		else:
			self.atomtree = "atui_nullstruct"

		if "name" in branch:
			self.name = branch["name"]
		elif "name" in branch_default:
			self.name = branch_default["name"]
		else:
			self.name = self.c_type

		if "description" in branch:
			self.description = branch["description"]
		elif "description" in branch_default:
			self.description = branch_default["description"]
		else:
			self.description = {}

		if "table_start" in branch:
			self.table_start = branch["table_start"]
		elif "table_start" in branch_default:
			self.table_start = branch_default["table_start"]
		else:
			self.table_start = "NULL"


		if "table_size" in branch:
			self.table_size = branch["table_size"]
		elif "table_size" in branch_default:
			self.table_size = branch_default["table_size"]
		else:
			self.table_size = "0"

		if "expanded" in branch:
			self.expanded = branch["expanded"]
		elif "expanded" in branch_default:
			self.expanded = branch_default["expanded"]
		else:
			self.expanded = True

		self.leaves = []
		if "leaves" in branch and populate_leaves:
			leaf_default:dict = defaults["leaf_defaults"]["generic"]#.copy()
			# parent_is_leaf should be set automatically by
			# branches_populate_defaults
			for leaf in branch["leaves"]:
				self.leaves.append(atui_leaf(leaf, defaults, leaf_default))

def branches_populate_defaults(
		defaults:dict
		):
	# defaults may not explicitly have every intended default catigory, so to
	# avoid existential conflict, create empty dicts.
	default_leaf_types:set = {"generic", "bitchild", "dynpattern"}
	leaves:dict
	if "leaf_defaults" in defaults:
		leaves = defaults["leaf_defaults"]
		leaf:str
		for leaf in leaves:
			default_leaf_types.remove(leaf)
	else:
		leaves = {}
		defaults["leaf_defaults"] = leaves

	name:str
	for name in default_leaf_types:
		leaves[name]:dict = {}
	
	for leaf_type in leaves:
		leaf = leaves[leaf_type]
		if "display" not in leaf:
			leaf["display"] = "ATUI_DISPLAY"
		leaf["parent_is_leaf"] = True
	leaves["generic"]["parent_is_leaf"] = False
	leaves["bitchild"]["fancy"] = "_ATUI_BITCHILD"
	
	if "branch_default" not in defaults:
		defaults["branch_default"] = {}


def leaf_to_subleaf(
		leaf:atui_leaf,
		indent:str
		) -> str:
	# if a leaf has sub leaves. See also: struct subleaf_meta
	child_indent:str = indent + "\t"
	bounds_template:str = (
"{\n"
+ child_indent + ".element_size = %s,\n"
+ child_indent + ".dynarray_length = %s,\n"
+ child_indent + ".deferred_start_array = %s,\n"
+ child_indent + ".numleaves = %u,\n"
+ child_indent + ".enum_taglist = %s,\n"
+ child_indent + ".sub_leaves = (atui_leaf const[%u]) {\n"
+ "%s"
+ child_indent + "},\n"
+ indent + "},"
)
	bounds_vals:tuple
	match (leaf.type.fancy):
		case atui_type.ATUI_DYNARRAY:
			if leaf.fancy_data["enum"] == "ATUI_NULL":
				enum_taglist = "NULL"
			else:
				enum_taglist = "&(ATUI_ENUM(%s))" % leaf.fancy_data["enum"]
			bounds_vals = (
				"sizeof(%s[0])" % leaf.access_meta,
				leaf.fancy_data["count"],
				str(not leaf.access).lower(),
				len(leaf.fancy_data["pattern"]),
				enum_taglist,
				len(leaf.fancy_data["pattern"]),
				leaves_to_text(leaf.fancy_data["pattern"], child_indent+"\t")
			)
		case atui_type.ATUI_BITFIELD:
			bounds_vals = (
				"0", "0", "0",
				len(leaf.fancy_data["fields"]),
				"NULL",
				len(leaf.fancy_data["fields"]),
				leaves_to_text(leaf.fancy_data["fields"], child_indent+"\t"),
			)
		case _:
			assert 0, (leaf.name, leaf.type.fancy)

	return bounds_template % bounds_vals

class leaf_type_to_text:
	fancy:str
	radix:str
	disable:str
	signed_num:str
	fraction:str
	enum_type:str
	enum_pointer:str

	def __init__(self,
			leaf:atui_leaf,
			var_meta:str
			):
		self.fancy = atui_type.ATUI_TYPE_FANCY[leaf.type.fancy]
		self.radix = atui_type.ATUI_TYPE_RADIX[leaf.type.radix]
		self.disable = atui_type.ATUI_TYPE_DISABLE[leaf.type.disable]
		self.signed_num = "_PPATUI_LEAF_SIGNED(%s)" % var_meta
		self.fraction = "_PPATUI_LEAF_FRACTION(%s)" % var_meta
		self.enum_type = "false"
		self.enum_pointer = "NULL"

		if (True == leaf.type.signed_num):
			self.signed_num = "true"
		if (True == leaf.type.fraction):
			self.fraction = "true"
		if (True == leaf.type.has_enum):
			# would be as simple as signed or fraction, but c _Generic() has
			# limitations around enums
			self.enum_type = "true"
			if leaf.enum is None:
				self.enum_pointer = "ATUI_ENUM_INFER(%s)" % var_meta
			else:
				self.enum_pointer = "&(ATUI_ENUM(%s))" % leaf.enum

def leaves_to_text(
		leaves:list,
		indent:str
		) -> str:
	# leaves to text meant for a segment of a c file
	child_indent:str = indent + "\t"
	leaf_template:str = (
indent + "{\n"
+ child_indent + ".name = \"%s\",\n"
+ child_indent + ".origname = \"%s\",\n"

+ child_indent + ".type = {\n"
+ child_indent + "	.fancy = %s,\n"
+ child_indent + "	.radix = %s,\n"
+ child_indent + "	.disable = %s,\n"
+ child_indent + "	.signed_num = %s,\n"
+ child_indent + "	.fraction = %s,\n"
+ child_indent + "	.has_enum = %s,\n"
+ child_indent + "},\n"
+ child_indent + ".enum_options = %s,\n"

+ child_indent + ".num_bytes = _PPATUI_NULLPTR_SIZE(%s),\n"
+ child_indent + ".array_size = 1,\n"
+ child_indent + ".fractional_bits = _PPATUI_LEAF_FIXED_FRACTION_BITS(%s),\n"
+ child_indent + ".total_bits = _PPATUI_LEAF_BITNESS(%s),\n"
+ child_indent + ".bitfield_hi = _PPATUI_LEAF_BITNESS(%s) - 1,\n"

+ child_indent + ".val = %s,\n"
+ child_indent + ".description = {%s},\n"
+ "%s" # extra
+ indent + "},\n"
)

	leaf_text_extra:str = "" # if there is any extra leaf elements
	var_meta:str = ""
	leaves_text:str = ""

	leaf:atui_leaf
	for leaf in leaves: # infer_leaf_data() may have other text gen
		if leaf.access:
			var_access = "&(%s)" % leaf.access
		else:
			var_access = "NULL"
		if leaf.access_meta:
			var_meta = leaf.access_meta
		else:
			var_meta = "NULL"
		match (leaf.type.fancy):
			case atui_type.ATUI_NOFANCY:
				leaf_text_extra = ""
			case atui_type.ATUI_STRING:
				if leaf.access:
					var_access = leaf.access
				leaf_text_extra = ""
			case atui_type.ATUI_ARRAY:
				if leaf.access:
					var_access = leaf.access
				leaf_text_extra = (
					child_indent + ".array_size = lengthof(%s),\n"
					+ child_indent + ".num_bytes = sizeof(%s),\n"
				)
				leaf_text_extra %= (leaf.access, leaf.access)
			case atui_type.ATUI_BITFIELD:
				leaf_text_extra = (
					child_indent + ".num_child_leaves = %u,\n"
					+ child_indent +
						".template_leaves = & (struct subleaf_meta const) %s\n"
				)
				leaf_text_extra %= (
					len(leaf.fancy_data["fields"]),
					leaf_to_subleaf(leaf, child_indent),
				)
			case atui_type._ATUI_BITCHILD:
				leaf_text_extra = (
					child_indent   + ".bitfield_hi = _PPATUI_BIT_HI(%s, %s),\n"
					+ child_indent + ".bitfield_lo = _PPATUI_BIT_LO(%s, %s),\n"
				)
				leaf_text_extra %= (
					leaf.union, leaf.access,
					leaf.union, leaf.access
				)
				var_access = "&(%s)" % leaf.access_meta
			case atui_type.ATUI_SHOOT | atui_type.ATUI_GRAFT: # fallthrough
				leaf_text_extra = (
					child_indent + ".branch_bud = _atui_%s,\n"
				)
				leaf_text_extra %= (leaf.fancy_data,)
			case atui_type.ATUI_DYNARRAY:
				if leaf.access:
					var_meta += "[0]"
					var_access = leaf.access
				else:
					var_access = leaf.fancy_data["deferred"]
				leaf_text_extra = (
					child_indent +
						".template_leaves = & (struct subleaf_meta const) %s\n"
				)
				leaf_text_extra %= (leaf_to_subleaf(leaf, child_indent),)
			case atui_type.ATUI_PETIOLE:
				leaf_text_extra = (
					child_indent
					+ ".template_branch = & (struct atui_branch_data const) {\n"
					+ "%s"
					+ child_indent + "},\n"
				)
				leaf_text_extra %= branch_embryo_to_text(
					leaf.fancy_data, child_indent + "\t"
				)
			case _:
				assert 0, (leaf.name, leaf.fancy)

		if leaf.parent_is_leaf:
			leaf_text_extra += child_indent + ".parent_is_leaf = true,\n"
		leaf.name:str = leaf.name.replace("\"","\\\"")

		type_text = leaf_type_to_text(leaf, var_meta)
		leaves_text += leaf_template % (
			leaf.name, leaf.name,

			type_text.fancy,      type_text.radix,  type_text.disable,
			type_text.signed_num, type_text.fraction,
			type_text.enum_type,  type_text.enum_pointer,

			var_meta, var_meta, var_meta, var_meta,
			var_access,
			description_to_text(leaf.description, child_indent),
			leaf_text_extra
		)
	return leaves_text

def leaves_asserts_to_text(
		leaves:list,
		indent:str
		) -> str:
	# various asserts and static_asserts over the leaves

	atui_auto_enum_index_assert:str = (
		"	static_assert(ATUI_ENUM_INDEXOF(%s) < ATUI_ENUM_ARRAY_LENGTH);"
		" // enum not registered\n"
	)
	atui_expl_enum_index_assert:str = (
		"	static_assert(ATUI_ENUM_INDEX(%s) < ATUI_ENUM_ARRAY_LENGTH);"
		" // enum not registered\n"
	)
	bitfield_assert:str = """\
	static_assert(sizeof(%s) == sizeof(%s)); // too big
	assert(((sizeof(%s)*CHAR_BIT) - 1) == _PPATUI_BIT_HI(%s, %s)); // not filled out
"""
	assert_text:str = ""
	var_meta:str = ""
	leaf:atui_leaf
	for leaf in leaves:
		if leaf.access_meta:
			var_meta = leaf.access_meta
		else:
			var_meta = "NULL"
		if (leaf.type.has_enum):
			if leaf.enum is None:
				assert_text += atui_auto_enum_index_assert % var_meta
			else:
				assert_text += atui_expl_enum_index_assert % leaf.enum
		match (leaf.type.fancy):
			case atui_type.ATUI_BITFIELD:
				highest_field:atui_leaf = leaf.fancy_data["fields"][-1]
				assert_text += bitfield_assert % (
					leaf.access, leaf.fancy_data["union"],
					leaf.access, leaf.fancy_data["union"], highest_field.access
				)

	return assert_text

class deep_count_leaves:
	leaves:int = 0
	graft:int = 0
	shoot:int = 0
	dyn_leaves:str = "0"
	dyn_graft:str = "0"
	dyn_shoot:str = "0"

	nest_dynarray:str = "+ (%s * (%u + %s))"
	def __init__(self,
			leaves
			):
		# go through all the leaves, recursively, to develop a string
		self.leaves += len(leaves)
		for leaf in leaves:
			match (leaf.type.fancy):
				case atui_type.ATUI_GRAFT:
					self.graft += 1
				case atui_type.ATUI_SHOOT | atui_type.ATUI_PETIOLE:
					self.shoot += 1
				case atui_type.ATUI_DYNARRAY:
					# We're in dynarray. The dynarray segments of subcounters
					# will be non-'0' if there is a nested dynarray.
					dynlength:str = leaf.fancy_data["count"]
					sub_counters = deep_count_leaves(leaf.fancy_data["pattern"])
					self.dyn_leaves += self.nest_dynarray % (
						dynlength, sub_counters.leaves, sub_counters.dyn_leaves
					)
					self.dyn_graft += self.nest_dynarray % (
						dynlength, sub_counters.graft, sub_counters.dyn_graft
					)
					self.dyn_shoot += self.nest_dynarray % (
						dynlength, sub_counters.shoot, sub_counters.dyn_shoot
					)

def branch_embryo_to_text(
		branch:atui_branch,
		indent:str
		) -> str:
	child_indent:str = indent + "\t"
	embryo_template:str = (
indent + ".seed = {\n"
+ indent + "	.name = \"%s\",\n"
+ indent + "	.origname = \"%s\",\n"
+ indent + "	.structname = \"%s\",\n"
+ indent + "	.description = {%s},\n"
+ indent + "	.table_start = (void*) (%s),\n"
+ indent + "	.table_size = (%s),\n"
+ indent + "	.prefer_contiguous = (\n"
+ indent + "		(0 < _PPATUI_NULLPTR_SIZE(*bios))\n"
+ indent + "		&& (\n"
+ indent + "			%s\n"
+ indent + "			<= _PPATUI_NULLPTR_SIZE(*bios)\n"
+ indent + "		)\n"
+ indent + "	),\n"
+ indent + "	.expanded = %s,\n"
+ indent + "},\n"
+ indent + ".computed_num_leaves = %s,\n"
+ indent + ".computed_num_graft = %s,\n"
+ indent + ".computed_num_shoot = %s,\n"
+ indent + ".num_leaves_init = %u,\n"
+ indent + ".leaves_init = (atui_leaf const[]) {\n"
+ "%s"
+ indent + "},\n"
)
	counters = deep_count_leaves(branch.leaves)
	embryo_text:str = embryo_template % (
		branch.name, branch.name, branch.c_type, # embryo
		description_to_text(branch.description, child_indent),
		branch.table_start, branch.table_size, branch.table_size,
		str(branch.expanded).lower(),

		"(%u + %s)" % (counters.leaves, counters.dyn_leaves), # 'computed'
		"(%u + %s)" % (counters.graft, counters.dyn_graft),
		"(%u + %s)" % (counters.shoot, counters.dyn_shoot),

		len(branch.leaves),  leaves_to_text(branch.leaves, child_indent),
	)
	return embryo_text

def branches_to_c(
		atui_data:dict,
		fname:str
		) -> str:
	# atui branches to text meant for a c file
	assert(atui_data["class"] == "branch")
	assert(type(atui_data["branches"]) is list)

	branches:list = []
	branch:atui_branch = None
	defaults:dict = atui_data["global_defaults"]
	branches_populate_defaults(defaults)
	for bd in atui_data["branches"]:
		branches.append(atui_branch(bd, defaults))

	cfile_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#include "standard.h"
#include "atomtree.h"
#include "atui.h"
#include "atui_allocator.h"
"""
# These arrays need to be in a function to handle the bios-> and atomtree->
# everywhere. trying to globalise the vars gets annoying real fast.
	branch_template:str = """
atui_branch* 
_atui_%s(
		atuifunc_args const* const args
		) {
	%s %s const* const bios = args->bios;
	struct %s const* const atomtree = args->atomtree;

	struct atui_branch_data const branch_embryo = {
%s\
	};

%s\

	assert(branch_embryo.computed_num_leaves < UINT16_MAX);
	assert(branch_embryo.computed_num_graft < UINT8_MAX);
	assert(branch_embryo.computed_num_shoot < UINT8_MAX);

	return atui_branch_allocator(&branch_embryo, args);
}
"""

	dynarray_patterns_text:str = ""
	dynarray_bounds_text:str = ""
	num_graft:int = 0
	num_shoot:int = 0

	# for deep count

	out_text:str = cfile_header
	branch:atui_branch
	for branch in branches:
		out_text += branch_template % (
			branch.name, branch.c_prefix, branch.c_type, branch.atomtree,

			branch_embryo_to_text(branch, "\t\t"),		

			leaves_asserts_to_text(branch.leaves, "\t"),
		)
	return out_text


def branches_to_h(
		atui_data:dict,
		fname:str
		) -> str:
	# c header defines from atui branches
	assert (atui_data["class"] == "branch"), fname
	assert (type(atui_data["branches"]) is list), fname

	header_header:str = """\
/* Autogenerated with ppatui.py. Do not edit. */

#ifndef %s_H
#define %s_H

"""
	header_entry:str = """\
atui_branch*
_atui_%s(
		atuifunc_args const* args
		);
"""
	header_ender:str = "\n#endif\n"

	out_text:str = header_header % (fname.upper(), fname.upper())
	branch:atui_branch = None
	defaults:dict = atui_data["global_defaults"]
	branches_populate_defaults(defaults)
	bd:dict
	for bd in atui_data["branches"]:
		out_text += header_entry % atui_branch(bd, defaults, False).name

	return out_text + header_ender


def parse_args(
		argv:list
		) -> argparse.Namespace:
	parser:argparse.ArgumentParser = argparse.ArgumentParser()
	parser.add_argument("-o", "--output", required=True, nargs=1)
	parser.add_argument("-i", "--inputs", required=True, nargs='*')
	modes = parser.add_mutually_exclusive_group(required=True)
	modes.add_argument("-s", "--source", action="store_true")
	modes.add_argument("-d", "--header", action="store_true")
	return parser.parse_args(argv)
def intend_source(
		atui_data:dict
		) -> Callable:
	assert ("class" in atui_data)
	match (atui_data["class"]):
		case "branch": return branches_to_c
		case "enum": return enum_to_c
		case "array": return array_to_c
		case "searchfield": return searchfield_to_c
		case "pci_id_lut": return pcilut_to_c
		case _: assert 0
def intend_header(
		atui_data:dict
		) -> Callable:
	assert ("class" in atui_data)
	match (atui_data["class"]):
		case "branch": return branches_to_h
		case "enum": return enum_to_h
		case "array": return array_to_h
		case "searchfield": return searchfield_to_h
		case "pci_id_lut": return pcilut_to_h
		case _: assert 0
def get_intent( # cli argument handling
		intent:argparse.Namespace
		) -> Callable:
	if intent.source:
		return intend_source
	elif intent.header:
		return intend_header
	else:
		assert 0

def main(
		argc:int,
		argv:list
		):
	args:argparse.Namespace = parse_args(argv[1:])

	# a function call that returns a function to select which final function to
	# use
	get_mode:Callable = get_intent(args)
	atui_data:dict = {}
	output_text:str = ""
	infile:str
	for infile in args.inputs:
		with open(infile, 'r', encoding="utf-8") as f:
			atui_data = json5.load(f)
		mode_func:Callable = get_mode(atui_data)
		output_text += mode_func(atui_data, pathlib.Path(infile).stem)

	with open(args.output[0], 'w', encoding="utf-8") as f:
		f.write(output_text)

if (__name__ == "__main__"):
	sys.exit(main(len(sys.argv), sys.argv))
