#ifndef ATOMTREE_TOOLS_H
#define ATOMTREE_TOOLS_H

struct atomtree_init_reg_block;
#include "asic_reg_tools.h"

// ppatui.py autogenerated:
#include "asic_reg_indices.h"


typedef struct atomtree_atom {
	struct atom_common_table_header* table_header;
	semver ver;
} atomtree_atom;
#define atomtree_atomise(punning_structs)\
	union {\
		atomtree_atom atom;\
		struct {\
			union {\
				struct atom_common_table_header* table_header;\
				punning_structs\
			};\
			semver ver;\
		};\
	};

#endif
