/*
Enums for ATUI_ENUM
See ppatui.h for PPATUI_ENUMER() definition
See atui_atomfirmware.c for purpose
*/

/*
def enum_to_atui(s):
	import re
	s = re.sub("\n    ","\n\t", s)
	s = re.sub("enum\s+([a-zA-Z0-9_]+).*{", "PPATUI_ENUMER(\g<1>,", s)
	s = re.sub("\t([a-zA-Z0-9_]+).*\n","\t\g<1>,\n",s)
	s = re.sub(",\n};","\n)",s)
	print(s)

enum_to_atui(s)


*/
#ifndef ATUI_ENUMS_H
#define ATUI_ENUMS_H

PPATUI_ENUMER(I2cControllerPort_e,
	I2C_CONTROLLER_PORT_0,
	I2C_CONTROLLER_PORT_1
)
PPATUI_ENUMER(I2cControllerName_e,
	I2C_CONTROLLER_NAME_VR_GFX,
	I2C_CONTROLLER_NAME_VR_SOC,
	I2C_CONTROLLER_NAME_VR_VDDCI,
	I2C_CONTROLLER_NAME_VR_MVDD,
	I2C_CONTROLLER_NAME_LIQUID_0,
	I2C_CONTROLLER_NAME_LIQUID_1,
	I2C_CONTROLLER_NAME_PLX,
	I2C_CONTROLLER_NAME_COUNT
)
PPATUI_ENUMER(I2cControllerThrottler_e,
	I2C_CONTROLLER_THROTTLER_TYPE_NONE,
	I2C_CONTROLLER_THROTTLER_VR_GFX,
	I2C_CONTROLLER_THROTTLER_VR_SOC,
	I2C_CONTROLLER_THROTTLER_VR_VDDCI,
	I2C_CONTROLLER_THROTTLER_VR_MVDD,
	I2C_CONTROLLER_THROTTLER_LIQUID_0,
	I2C_CONTROLLER_THROTTLER_LIQUID_1,
	I2C_CONTROLLER_THROTTLER_PLX
)
PPATUI_ENUMER(I2cControllerProtocol_e,
	I2C_CONTROLLER_PROTOCOL_VR_XPDE132G5,
	I2C_CONTROLLER_PROTOCOL_VR_IR35217,
	I2C_CONTROLLER_PROTOCOL_TMP_TMP102A,
	I2C_CONTROLLER_PROTOCOL_SPARE_0,
	I2C_CONTROLLER_PROTOCOL_SPARE_1,
	I2C_CONTROLLER_PROTOCOL_SPARE_2
)
PPATUI_ENUMER(I2cControllerSpeed_e,
	I2C_CONTROLLER_SPEED_SLOW,
	I2C_CONTROLLER_SPEED_FAST
)


PPATUI_ENUMER(smudpm_v4_5_i2ccontrollerspeed_e,
	SMC_V4_5_I2C_CONTROLLER_SPEED_SLOW,
	SMC_V4_5_I2C_CONTROLLER_SPEED_FAST
)
PPATUI_ENUMER(smudpm_v4_5_i2ccontrollerport_e,
	SMC_V4_5_I2C_CONTROLLER_PORT_0,
	SMC_V4_5_I2C_CONTROLLER_PORT_1
)
PPATUI_ENUMER(smudpm_v4_5_i2ccontrollername_e,
	SMC_V4_5_I2C_CONTROLLER_NAME_VR_GFX,
	SMC_V4_5_I2C_CONTROLLER_NAME_VR_SOC,
	SMC_V4_5_I2C_CONTROLLER_NAME_VR_VDDCI,
	SMC_V4_5_I2C_CONTROLLER_NAME_VR_MVDD,
	SMC_V4_5_I2C_CONTROLLER_NAME_LIQUID0,
	SMC_V4_5_I2C_CONTROLLER_NAME_LIQUID1,
	SMC_V4_5_I2C_CONTROLLER_NAME_PLX,
	SMC_V4_5_I2C_CONTROLLER_NAME_SPARE,
	SMC_V4_5_I2C_CONTROLLER_NAME_COUNT
)
PPATUI_ENUMER(smudpm_v4_5_i2ccontrollerthrottler_e,
	SMC_V4_5_I2C_CONTROLLER_THROTTLER_TYPE_NONE,
	SMC_V4_5_I2C_CONTROLLER_THROTTLER_VR_GFX,
	SMC_V4_5_I2C_CONTROLLER_THROTTLER_VR_SOC,
	SMC_V4_5_I2C_CONTROLLER_THROTTLER_VR_VDDCI,
	SMC_V4_5_I2C_CONTROLLER_THROTTLER_VR_MVDD,
	SMC_V4_5_I2C_CONTROLLER_THROTTLER_LIQUID0,
	SMC_V4_5_I2C_CONTROLLER_THROTTLER_LIQUID1,
	SMC_V4_5_I2C_CONTROLLER_THROTTLER_PLX,
	SMC_V4_5_I2C_CONTROLLER_THROTTLER_COUNT
)
PPATUI_ENUMER(smudpm_v4_5_i2ccontrollerprotocol_e,
	SMC_V4_5_I2C_CONTROLLER_PROTOCOL_VR_0,
	SMC_V4_5_I2C_CONTROLLER_PROTOCOL_VR_1,
	SMC_V4_5_I2C_CONTROLLER_PROTOCOL_TMP_0,
	SMC_V4_5_I2C_CONTROLLER_PROTOCOL_TMP_1,
	SMC_V4_5_I2C_CONTROLLER_PROTOCOL_SPARE_0,
	SMC_V4_5_I2C_CONTROLLER_PROTOCOL_SPARE_1,
	SMC_V4_5_I2C_CONTROLLER_PROTOCOL_COUNT
)



PPATUI_ENUMER(atom_lcd_info_panel_misc,
	ATOM_PANEL_MISC_FPDI
)
PPATUI_ENUMER(atom_lcd_info_dptolvds_rx_id,
	eDP_TO_LVDS_RX_DISABLE,
	eDP_TO_LVDS_COMMON_ID,
	eDP_TO_LVDS_REALTEK_ID
)



PPATUI_ENUMER(atom_spread_spectrum_mode,
	ATOM_SS_CENTER_OR_DOWN_MODE_MASK,
	ATOM_SS_DOWN_SPREAD_MODE,
	ATOM_SS_CENTRE_SPREAD_MODE,
	ATOM_INT_OR_EXT_SS_MASK,
	ATOM_INTERNAL_SS_MASK,
	ATOM_EXTERNAL_SS_MASK
)


PPATUI_ENUMER(atom_dgpu_vram_type,
	ATOM_DGPU_VRAM_TYPE_GDDR5,
	ATOM_DGPU_VRAM_TYPE_HBM2,
	ATOM_DGPU_VRAM_TYPE_HBM2E,
	ATOM_DGPU_VRAM_TYPE_GDDR6,
	ATOM_DGPU_VRAM_TYPE_HBM3
)



PPATUI_ENUMER(atom_voltage_type,
	VOLTAGE_TYPE_VDDC,
	VOLTAGE_TYPE_MVDDC,
	VOLTAGE_TYPE_MVDDQ,
	VOLTAGE_TYPE_VDDCI,
	VOLTAGE_TYPE_VDDGFX,
	VOLTAGE_TYPE_PCC,
	VOLTAGE_TYPE_MVPP,
	VOLTAGE_TYPE_LEDDPM,
	VOLTAGE_TYPE_PCC_MVDD,
	VOLTAGE_TYPE_PCIE_VDDC,
	VOLTAGE_TYPE_PCIE_VDDR,
	VOLTAGE_TYPE_GENERIC_I2C_1,
	VOLTAGE_TYPE_GENERIC_I2C_2,
	VOLTAGE_TYPE_GENERIC_I2C_3,
	VOLTAGE_TYPE_GENERIC_I2C_4,
	VOLTAGE_TYPE_GENERIC_I2C_5,
	VOLTAGE_TYPE_GENERIC_I2C_6,
	VOLTAGE_TYPE_GENERIC_I2C_7,
	VOLTAGE_TYPE_GENERIC_I2C_8,
	VOLTAGE_TYPE_GENERIC_I2C_9,
	VOLTAGE_TYPE_GENERIC_I2C_10
)
PPATUI_ENUMER(atom_voltage_object_mode,
	VOLTAGE_OBJ_GPIO_LUT,
	VOLTAGE_OBJ_VR_I2C_INIT_SEQ,
	VOLTAGE_OBJ_PHASE_LUT,
	VOLTAGE_OBJ_SVID2,
	VOLTAGE_OBJ_EVV,
	VOLTAGE_OBJ_MERGED_POWER
)

#endif
