/*
autogenerated with asic_reg.py
Considers GMC versions: 6_0, 7_0, 7_1, 8_1, 8_2
*/

#ifndef GMC_ATUI_INCLUDE_H
#define GMC_ATUI_INCLUDE_H

PPATUI_HEADERIFY(atc_ats_cntl_6_0);

PPATUI_HEADERIFY(atc_ats_debug_6_0);
PPATUI_HEADERIFY(atc_ats_debug_7_0);
PPATUI_HEADERIFY(atc_ats_debug_7_1);
PPATUI_HEADERIFY(atc_ats_debug_8_1);

PPATUI_HEADERIFY(atc_ats_default_page_cntl_6_0);
PPATUI_HEADERIFY(atc_ats_default_page_cntl_8_1);

PPATUI_HEADERIFY(atc_ats_default_page_low_6_0);
PPATUI_HEADERIFY(atc_ats_default_page_low_8_1);

PPATUI_HEADERIFY(atc_ats_fault_cntl_6_0);
PPATUI_HEADERIFY(atc_ats_fault_cntl_8_1);

PPATUI_HEADERIFY(atc_ats_fault_debug_6_0);

PPATUI_HEADERIFY(atc_ats_fault_status_addr_6_0);

PPATUI_HEADERIFY(atc_ats_fault_status_info_6_0);
PPATUI_HEADERIFY(atc_ats_fault_status_info_8_1);

PPATUI_HEADERIFY(atc_ats_fault_status_info2_8_1);

PPATUI_HEADERIFY(atc_ats_smu_status_8_1);

PPATUI_HEADERIFY(atc_ats_status_6_0);

PPATUI_HEADERIFY(atc_ats_vmid_status_8_1);

PPATUI_HEADERIFY(atc_l1_address_offset_6_0);

PPATUI_HEADERIFY(atc_l1_cntl_6_0);

PPATUI_HEADERIFY(atc_l1rd_debug2_tlb_8_1);

PPATUI_HEADERIFY(atc_l1rd_debug_tlb_6_0);
PPATUI_HEADERIFY(atc_l1rd_debug_tlb_7_0);

PPATUI_HEADERIFY(atc_l1rd_status_6_0);
PPATUI_HEADERIFY(atc_l1rd_status_8_1);

PPATUI_HEADERIFY(atc_l1wr_debug2_tlb_8_1);

PPATUI_HEADERIFY(atc_l1wr_debug_tlb_6_0);
PPATUI_HEADERIFY(atc_l1wr_debug_tlb_7_0);

PPATUI_HEADERIFY(atc_l1wr_status_6_0);
PPATUI_HEADERIFY(atc_l1wr_status_8_1);

PPATUI_HEADERIFY(atc_l2_cache_data0_8_1);

PPATUI_HEADERIFY(atc_l2_cache_data1_8_1);

PPATUI_HEADERIFY(atc_l2_cache_data2_8_1);

PPATUI_HEADERIFY(atc_l2_cntl_6_0);
PPATUI_HEADERIFY(atc_l2_cntl_7_0);

PPATUI_HEADERIFY(atc_l2_cntl2_7_0);

PPATUI_HEADERIFY(atc_l2_cntl3_8_1);

PPATUI_HEADERIFY(atc_l2_debug_6_0);
PPATUI_HEADERIFY(atc_l2_debug_8_1);

PPATUI_HEADERIFY(atc_l2_debug2_7_0);
PPATUI_HEADERIFY(atc_l2_debug2_7_1);
PPATUI_HEADERIFY(atc_l2_debug2_8_1);

PPATUI_HEADERIFY(atc_l2_status_8_1);

PPATUI_HEADERIFY(atc_l2_status2_8_1);

PPATUI_HEADERIFY(atc_misc_cg_6_0);

PPATUI_HEADERIFY(atc_perfcounter0_cfg_7_0);

PPATUI_HEADERIFY(atc_perfcounter1_cfg_7_0);

PPATUI_HEADERIFY(atc_perfcounter2_cfg_7_0);

PPATUI_HEADERIFY(atc_perfcounter3_cfg_7_0);

PPATUI_HEADERIFY(atc_perfcounter_hi_7_0);

PPATUI_HEADERIFY(atc_perfcounter_lo_7_0);

PPATUI_HEADERIFY(atc_perfcounter_rslt_cntl_7_0);

PPATUI_HEADERIFY(atc_vm_aperture0_cntl_6_0);

PPATUI_HEADERIFY(atc_vm_aperture0_cntl2_6_0);

PPATUI_HEADERIFY(atc_vm_aperture0_high_addr_6_0);

PPATUI_HEADERIFY(atc_vm_aperture0_low_addr_6_0);

PPATUI_HEADERIFY(atc_vm_aperture1_cntl_6_0);

PPATUI_HEADERIFY(atc_vm_aperture1_cntl2_6_0);

PPATUI_HEADERIFY(atc_vm_aperture1_high_addr_6_0);

PPATUI_HEADERIFY(atc_vm_aperture1_low_addr_6_0);

PPATUI_HEADERIFY(atc_vmid0_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid0_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid10_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid10_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid11_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid11_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid12_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid12_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid13_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid13_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid14_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid14_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid15_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid15_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid1_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid1_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid2_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid2_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid3_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid3_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid4_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid4_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid5_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid5_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid6_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid6_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid7_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid7_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid8_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid8_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid9_pasid_mapping_6_0);
PPATUI_HEADERIFY(atc_vmid9_pasid_mapping_8_1);

PPATUI_HEADERIFY(atc_vmid_pasid_mapping_update_status_6_0);

PPATUI_HEADERIFY(cc_mc_max_channel_6_0);

PPATUI_HEADERIFY(chub_atc_l1_debug_tlb_7_0);

PPATUI_HEADERIFY(chub_atc_l1_status_7_0);

PPATUI_HEADERIFY(chub_atc_perfcounter0_cfg_7_0);

PPATUI_HEADERIFY(chub_atc_perfcounter1_cfg_7_0);

PPATUI_HEADERIFY(chub_atc_perfcounter_hi_7_0);

PPATUI_HEADERIFY(chub_atc_perfcounter_lo_7_0);

PPATUI_HEADERIFY(chub_atc_perfcounter_rslt_cntl_7_0);

PPATUI_HEADERIFY(dll_cntl_6_0);

PPATUI_HEADERIFY(gmcon_debug_6_0);
PPATUI_HEADERIFY(gmcon_debug_8_1);

PPATUI_HEADERIFY(gmcon_lpt_target_7_1);

PPATUI_HEADERIFY(gmcon_mask_7_0);
PPATUI_HEADERIFY(gmcon_mask_7_1);

PPATUI_HEADERIFY(gmcon_misc_6_0);
PPATUI_HEADERIFY(gmcon_misc_7_0);

PPATUI_HEADERIFY(gmcon_misc2_6_0);
PPATUI_HEADERIFY(gmcon_misc2_7_0);
PPATUI_HEADERIFY(gmcon_misc2_7_1);

PPATUI_HEADERIFY(gmcon_misc3_6_0);
PPATUI_HEADERIFY(gmcon_misc3_7_0);
PPATUI_HEADERIFY(gmcon_misc3_7_1);

PPATUI_HEADERIFY(gmcon_perf_mon_cntl0_6_0);
PPATUI_HEADERIFY(gmcon_perf_mon_cntl0_7_1);

PPATUI_HEADERIFY(gmcon_perf_mon_cntl1_6_0);
PPATUI_HEADERIFY(gmcon_perf_mon_cntl1_7_1);

PPATUI_HEADERIFY(gmcon_perf_mon_rslt0_6_0);

PPATUI_HEADERIFY(gmcon_perf_mon_rslt1_6_0);

PPATUI_HEADERIFY(gmcon_pgfsm_config_6_0);

PPATUI_HEADERIFY(gmcon_pgfsm_read_6_0);

PPATUI_HEADERIFY(gmcon_pgfsm_write_6_0);

PPATUI_HEADERIFY(gmcon_reng_execute_6_0);

PPATUI_HEADERIFY(gmcon_reng_ram_data_6_0);

PPATUI_HEADERIFY(gmcon_reng_ram_index_6_0);

PPATUI_HEADERIFY(gmcon_stctrl_register_save_excl_set0_6_0);

PPATUI_HEADERIFY(gmcon_stctrl_register_save_excl_set1_6_0);

PPATUI_HEADERIFY(gmcon_stctrl_register_save_range0_6_0);

PPATUI_HEADERIFY(gmcon_stctrl_register_save_range1_6_0);

PPATUI_HEADERIFY(gmcon_stctrl_register_save_range2_6_0);

PPATUI_HEADERIFY(mc_arb_addr_hash_6_0);

PPATUI_HEADERIFY(mc_arb_addr_swiz0_7_0);

PPATUI_HEADERIFY(mc_arb_addr_swiz1_7_0);

PPATUI_HEADERIFY(mc_arb_age_cntl_7_0);
PPATUI_HEADERIFY(mc_arb_age_cntl_7_1);

PPATUI_HEADERIFY(mc_arb_age_rd_6_0);

PPATUI_HEADERIFY(mc_arb_age_wr_6_0);

PPATUI_HEADERIFY(mc_arb_atomic_8_1);

PPATUI_HEADERIFY(mc_arb_bankmap_6_0);

PPATUI_HEADERIFY(mc_arb_burst_time_8_1);
PPATUI_HEADERIFY(mc_arb_burst_time_6_0);

PPATUI_HEADERIFY(mc_arb_busy_status_7_0);
PPATUI_HEADERIFY(mc_arb_busy_status_8_1);

PPATUI_HEADERIFY(mc_arb_cac_cntl_6_0);

PPATUI_HEADERIFY(mc_arb_cg_6_0);
PPATUI_HEADERIFY(mc_arb_cg_7_0);

PPATUI_HEADERIFY(mc_arb_dram_timing_6_0);

PPATUI_HEADERIFY(mc_arb_dram_timing2_6_0);

PPATUI_HEADERIFY(mc_arb_dram_timing2_1_6_0);

PPATUI_HEADERIFY(mc_arb_dram_timing_1_6_0);

PPATUI_HEADERIFY(mc_arb_fed_cntl_6_0);
PPATUI_HEADERIFY(mc_arb_fed_cntl_7_0);

PPATUI_HEADERIFY(mc_arb_gdec_rd_cntl_6_0);

PPATUI_HEADERIFY(mc_arb_gdec_wr_cntl_6_0);

PPATUI_HEADERIFY(mc_arb_gecc2_6_0);
PPATUI_HEADERIFY(mc_arb_gecc2_7_0);

PPATUI_HEADERIFY(mc_arb_gecc2_cli_6_0);

PPATUI_HEADERIFY(mc_arb_gecc2_debug_6_0);

PPATUI_HEADERIFY(mc_arb_gecc2_debug2_6_0);

PPATUI_HEADERIFY(mc_arb_gecc2_misc_6_0);
PPATUI_HEADERIFY(mc_arb_gecc2_misc_7_0);
PPATUI_HEADERIFY(mc_arb_gecc2_misc_7_1);

PPATUI_HEADERIFY(mc_arb_gecc2_status_6_0);
PPATUI_HEADERIFY(mc_arb_gecc2_status_7_0);

PPATUI_HEADERIFY(mc_arb_grub_8_1);

PPATUI_HEADERIFY(mc_arb_grub2_8_1);

PPATUI_HEADERIFY(mc_arb_grub_priority1_rd_8_1);

PPATUI_HEADERIFY(mc_arb_grub_priority1_wr_8_1);

PPATUI_HEADERIFY(mc_arb_grub_priority2_rd_8_1);

PPATUI_HEADERIFY(mc_arb_grub_priority2_wr_8_1);

PPATUI_HEADERIFY(mc_arb_grub_promote_8_1);

PPATUI_HEADERIFY(mc_arb_grub_realtime_rd_8_1);

PPATUI_HEADERIFY(mc_arb_grub_realtime_wr_8_1);

PPATUI_HEADERIFY(mc_arb_harsh_bwcnt0_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_bwcnt0_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_bwcnt1_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_bwcnt1_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_bwperiod0_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_bwperiod0_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_bwperiod1_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_bwperiod1_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_ctl_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_ctl_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_en_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_en_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_sat0_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_sat0_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_sat1_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_sat1_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_tx_hi0_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_tx_hi0_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_tx_hi1_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_tx_hi1_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_tx_lo0_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_tx_lo0_wr_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_tx_lo1_rd_7_0);

PPATUI_HEADERIFY(mc_arb_harsh_tx_lo1_wr_7_0);

PPATUI_HEADERIFY(mc_arb_lazy0_rd_6_0);

PPATUI_HEADERIFY(mc_arb_lazy0_wr_6_0);

PPATUI_HEADERIFY(mc_arb_lazy1_rd_6_0);

PPATUI_HEADERIFY(mc_arb_lazy1_wr_6_0);

PPATUI_HEADERIFY(mc_arb_lm_rd_6_0);

PPATUI_HEADERIFY(mc_arb_lm_wr_6_0);
PPATUI_HEADERIFY(mc_arb_lm_wr_7_1);
PPATUI_HEADERIFY(mc_arb_lm_wr_8_1);

PPATUI_HEADERIFY(mc_arb_max_lat_cid_7_0);

PPATUI_HEADERIFY(mc_arb_max_lat_rslt0_7_0);

PPATUI_HEADERIFY(mc_arb_max_lat_rslt1_7_0);

PPATUI_HEADERIFY(mc_arb_minclks_6_0);
PPATUI_HEADERIFY(mc_arb_minclks_7_0);

PPATUI_HEADERIFY(mc_arb_misc_6_0);
PPATUI_HEADERIFY(mc_arb_misc_7_0);

PPATUI_HEADERIFY(mc_arb_misc2_6_0);

PPATUI_HEADERIFY(mc_arb_misc3_7_0);
PPATUI_HEADERIFY(mc_arb_misc3_7_1);
PPATUI_HEADERIFY(mc_arb_misc3_8_1);

PPATUI_HEADERIFY(mc_arb_perf_cid_7_1);

PPATUI_HEADERIFY(mc_arb_perf_mon_cntl0_ecc_7_0);

PPATUI_HEADERIFY(mc_arb_perfcounter0_cfg_7_0);

PPATUI_HEADERIFY(mc_arb_perfcounter1_cfg_7_0);

PPATUI_HEADERIFY(mc_arb_perfcounter2_cfg_7_0);

PPATUI_HEADERIFY(mc_arb_perfcounter3_cfg_7_0);

PPATUI_HEADERIFY(mc_arb_perfcounter_hi_7_0);

PPATUI_HEADERIFY(mc_arb_perfcounter_lo_7_0);

PPATUI_HEADERIFY(mc_arb_perfcounter_rslt_cntl_7_0);

PPATUI_HEADERIFY(mc_arb_pm_cntl_6_0);
PPATUI_HEADERIFY(mc_arb_pm_cntl_7_0);
PPATUI_HEADERIFY(mc_arb_pm_cntl_8_1);

PPATUI_HEADERIFY(mc_arb_pop_6_0);

PPATUI_HEADERIFY(mc_arb_ramcfg_6_0);
PPATUI_HEADERIFY(mc_arb_ramcfg_7_0);

PPATUI_HEADERIFY(mc_arb_remreq_6_0);
PPATUI_HEADERIFY(mc_arb_remreq_7_0);

PPATUI_HEADERIFY(mc_arb_replay_6_0);
PPATUI_HEADERIFY(mc_arb_replay_7_0);

PPATUI_HEADERIFY(mc_arb_ret_credits2_7_0);
PPATUI_HEADERIFY(mc_arb_ret_credits2_7_1);
PPATUI_HEADERIFY(mc_arb_ret_credits2_8_1);

PPATUI_HEADERIFY(mc_arb_ret_credits_rd_6_0);

PPATUI_HEADERIFY(mc_arb_ret_credits_wr_6_0);
PPATUI_HEADERIFY(mc_arb_ret_credits_wr_7_1);

PPATUI_HEADERIFY(mc_arb_rfsh_cntl_6_0);
PPATUI_HEADERIFY(mc_arb_rfsh_cntl_8_1);
PPATUI_HEADERIFY(mc_arb_rfsh_cntl_7_1);

PPATUI_HEADERIFY(mc_arb_rfsh_rate_6_0);

PPATUI_HEADERIFY(mc_arb_rtt_cntl0_6_0);

PPATUI_HEADERIFY(mc_arb_rtt_cntl1_6_0);

PPATUI_HEADERIFY(mc_arb_rtt_cntl2_6_0);

PPATUI_HEADERIFY(mc_arb_rtt_data_6_0);

PPATUI_HEADERIFY(mc_arb_rtt_debug_6_0);

PPATUI_HEADERIFY(mc_arb_snoop_8_1);

PPATUI_HEADERIFY(mc_arb_sqm_cntl_6_0);
PPATUI_HEADERIFY(mc_arb_sqm_cntl_7_0);

PPATUI_HEADERIFY(mc_arb_ssm_7_0);

PPATUI_HEADERIFY(mc_arb_tm_cntl_rd_6_0);

PPATUI_HEADERIFY(mc_arb_tm_cntl_wr_6_0);

PPATUI_HEADERIFY(mc_arb_wcdr_6_0);

PPATUI_HEADERIFY(mc_arb_wcdr_2_6_0);

PPATUI_HEADERIFY(mc_arb_wtm_cntl_rd_6_0);
PPATUI_HEADERIFY(mc_arb_wtm_cntl_rd_7_0);

PPATUI_HEADERIFY(mc_arb_wtm_cntl_wr_6_0);
PPATUI_HEADERIFY(mc_arb_wtm_cntl_wr_7_0);

PPATUI_HEADERIFY(mc_arb_wtm_grpwt_rd_6_0);

PPATUI_HEADERIFY(mc_arb_wtm_grpwt_wr_6_0);

PPATUI_HEADERIFY(mc_bist_auto_cntl_6_0);

PPATUI_HEADERIFY(mc_bist_cmd_cntl_6_0);

PPATUI_HEADERIFY(mc_bist_cmp_cntl_6_0);

PPATUI_HEADERIFY(mc_bist_cmp_cntl_2_6_0);

PPATUI_HEADERIFY(mc_bist_cntl_6_0);

PPATUI_HEADERIFY(mc_bist_data_mask_6_0);

PPATUI_HEADERIFY(mc_bist_data_word0_6_0);

PPATUI_HEADERIFY(mc_bist_data_word1_6_0);

PPATUI_HEADERIFY(mc_bist_data_word2_6_0);

PPATUI_HEADERIFY(mc_bist_data_word3_6_0);

PPATUI_HEADERIFY(mc_bist_data_word4_6_0);

PPATUI_HEADERIFY(mc_bist_data_word5_6_0);

PPATUI_HEADERIFY(mc_bist_data_word6_6_0);

PPATUI_HEADERIFY(mc_bist_data_word7_6_0);

PPATUI_HEADERIFY(mc_bist_dir_cntl_6_0);

PPATUI_HEADERIFY(mc_bist_eaddr_6_0);

PPATUI_HEADERIFY(mc_bist_mismatch_addr_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_edc_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_mask_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_word0_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_word1_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_word2_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_word3_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_word4_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_word5_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_word6_6_0);

PPATUI_HEADERIFY(mc_bist_rdata_word7_6_0);

PPATUI_HEADERIFY(mc_bist_saddr_6_0);

PPATUI_HEADERIFY(mc_cg_config_6_0);

PPATUI_HEADERIFY(mc_cg_config_mcd_6_0);
PPATUI_HEADERIFY(mc_cg_config_mcd_7_1);

PPATUI_HEADERIFY(mc_cg_dataport_6_0);

PPATUI_HEADERIFY(mc_citf_cntl_6_0);
PPATUI_HEADERIFY(mc_citf_cntl_7_0);
PPATUI_HEADERIFY(mc_citf_cntl_7_1);

PPATUI_HEADERIFY(mc_citf_credits_arb_rd_6_0);

PPATUI_HEADERIFY(mc_citf_credits_arb_rd2_8_1);

PPATUI_HEADERIFY(mc_citf_credits_arb_wr_6_0);
PPATUI_HEADERIFY(mc_citf_credits_arb_wr_7_1);

PPATUI_HEADERIFY(mc_citf_credits_vm_6_0);

PPATUI_HEADERIFY(mc_citf_credits_xbar_6_0);

PPATUI_HEADERIFY(mc_citf_dagb_cntl_6_0);

PPATUI_HEADERIFY(mc_citf_dagb_dly_6_0);
PPATUI_HEADERIFY(mc_citf_dagb_dly_7_1);
PPATUI_HEADERIFY(mc_citf_dagb_dly_8_1);

PPATUI_HEADERIFY(mc_citf_int_credits_6_0);

PPATUI_HEADERIFY(mc_citf_int_credits_wr_6_0);

PPATUI_HEADERIFY(mc_citf_misc_rd_cg_6_0);

PPATUI_HEADERIFY(mc_citf_misc_vm_cg_6_0);

PPATUI_HEADERIFY(mc_citf_misc_wr_cg_6_0);

PPATUI_HEADERIFY(mc_citf_perf_mon_cntl2_6_0);
PPATUI_HEADERIFY(mc_citf_perf_mon_cntl2_7_0);

PPATUI_HEADERIFY(mc_citf_perf_mon_rslt2_6_0);
PPATUI_HEADERIFY(mc_citf_perf_mon_rslt2_8_1);

PPATUI_HEADERIFY(mc_citf_perfcounter0_cfg_7_0);

PPATUI_HEADERIFY(mc_citf_perfcounter1_cfg_7_0);

PPATUI_HEADERIFY(mc_citf_perfcounter2_cfg_7_0);

PPATUI_HEADERIFY(mc_citf_perfcounter3_cfg_7_0);

PPATUI_HEADERIFY(mc_citf_perfcounter_hi_7_0);

PPATUI_HEADERIFY(mc_citf_perfcounter_lo_7_0);

PPATUI_HEADERIFY(mc_citf_perfcounter_rslt_cntl_7_0);

PPATUI_HEADERIFY(mc_citf_remreq_6_0);

PPATUI_HEADERIFY(mc_citf_ret_mode_6_0);
PPATUI_HEADERIFY(mc_citf_ret_mode_7_1);

PPATUI_HEADERIFY(mc_citf_wtm_rd_cntl_6_0);
PPATUI_HEADERIFY(mc_citf_wtm_rd_cntl_7_0);

PPATUI_HEADERIFY(mc_citf_wtm_wr_cntl_6_0);
PPATUI_HEADERIFY(mc_citf_wtm_wr_cntl_7_0);

PPATUI_HEADERIFY(mc_citf_xtra_enable_6_0);
PPATUI_HEADERIFY(mc_citf_xtra_enable_7_0);

PPATUI_HEADERIFY(mc_config_6_0);
PPATUI_HEADERIFY(mc_config_7_1);

PPATUI_HEADERIFY(mc_config_mcd_6_0);
PPATUI_HEADERIFY(mc_config_mcd_7_1);

PPATUI_HEADERIFY(mc_dlb_config0_7_1);

PPATUI_HEADERIFY(mc_dlb_config1_7_1);

PPATUI_HEADERIFY(mc_dlb_miscctrl0_7_1);

PPATUI_HEADERIFY(mc_dlb_miscctrl1_7_1);

PPATUI_HEADERIFY(mc_dlb_miscctrl2_7_1);

PPATUI_HEADERIFY(mc_dlb_setup_7_1);

PPATUI_HEADERIFY(mc_dlb_setupfifo_7_1);

PPATUI_HEADERIFY(mc_dlb_setupsweep_7_1);

PPATUI_HEADERIFY(mc_dlb_status_7_1);

PPATUI_HEADERIFY(mc_dlb_status_misc0_7_1);

PPATUI_HEADERIFY(mc_dlb_status_misc1_7_1);

PPATUI_HEADERIFY(mc_dlb_status_misc2_7_1);

PPATUI_HEADERIFY(mc_dlb_status_misc3_7_1);

PPATUI_HEADERIFY(mc_dlb_status_misc4_7_1);

PPATUI_HEADERIFY(mc_dlb_status_misc5_7_1);

PPATUI_HEADERIFY(mc_dlb_status_misc6_7_1);

PPATUI_HEADERIFY(mc_dlb_status_misc7_7_1);

PPATUI_HEADERIFY(mc_dlb_write_mask_7_1);

PPATUI_HEADERIFY(mc_fus_arb_garlic_cntl_7_0);

PPATUI_HEADERIFY(mc_fus_arb_garlic_isoc_pri_7_0);

PPATUI_HEADERIFY(mc_fus_arb_garlic_wr_pri_7_0);

PPATUI_HEADERIFY(mc_fus_arb_garlic_wr_pri2_7_0);

PPATUI_HEADERIFY(mc_fus_dram0_bank_addr_mapping_7_0);

PPATUI_HEADERIFY(mc_fus_dram0_cs0_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram0_cs1_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram0_cs2_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram0_cs3_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram0_ctl_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram0_ctl_limit_7_0);

PPATUI_HEADERIFY(mc_fus_dram1_bank_addr_mapping_7_0);

PPATUI_HEADERIFY(mc_fus_dram1_cs0_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram1_cs1_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram1_cs2_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram1_cs3_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram1_ctl_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram1_ctl_limit_7_0);

PPATUI_HEADERIFY(mc_fus_dram_aper_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram_aper_def_7_0);

PPATUI_HEADERIFY(mc_fus_dram_aper_top_7_0);

PPATUI_HEADERIFY(mc_fus_dram_c6save_aper_base_7_0);

PPATUI_HEADERIFY(mc_fus_dram_c6save_aper_top_7_0);

PPATUI_HEADERIFY(mc_fus_dram_ctl_high_01_7_0);

PPATUI_HEADERIFY(mc_fus_dram_ctl_high_23_7_0);

PPATUI_HEADERIFY(mc_fus_dram_mode_7_0);
PPATUI_HEADERIFY(mc_fus_dram_mode_8_2);

PPATUI_HEADERIFY(mc_grub_features_8_2);

PPATUI_HEADERIFY(mc_grub_perfcounter0_cfg_8_2);

PPATUI_HEADERIFY(mc_grub_perfcounter1_cfg_8_2);

PPATUI_HEADERIFY(mc_grub_perfcounter_hi_8_2);

PPATUI_HEADERIFY(mc_grub_perfcounter_lo_8_2);

PPATUI_HEADERIFY(mc_grub_perfcounter_rslt_cntl_8_2);

PPATUI_HEADERIFY(mc_grub_post_probe_delay_8_2);

PPATUI_HEADERIFY(mc_grub_probe_credits_8_2);

PPATUI_HEADERIFY(mc_grub_probe_map_8_2);

PPATUI_HEADERIFY(mc_grub_tcb_data_hi_8_2);

PPATUI_HEADERIFY(mc_grub_tcb_data_lo_8_2);

PPATUI_HEADERIFY(mc_grub_tcb_index_8_2);

PPATUI_HEADERIFY(mc_grub_tx_credits_8_2);

PPATUI_HEADERIFY(mc_hub_misc_atomic_idle_status_8_1);
PPATUI_HEADERIFY(mc_hub_misc_atomic_idle_status_8_2);

PPATUI_HEADERIFY(mc_hub_misc_dbg_6_0);
PPATUI_HEADERIFY(mc_hub_misc_dbg_7_0);

PPATUI_HEADERIFY(mc_hub_misc_framing_6_0);

PPATUI_HEADERIFY(mc_hub_misc_hub_cg_6_0);

PPATUI_HEADERIFY(mc_hub_misc_idle_status_6_0);
PPATUI_HEADERIFY(mc_hub_misc_idle_status_7_0);
PPATUI_HEADERIFY(mc_hub_misc_idle_status_7_1);
PPATUI_HEADERIFY(mc_hub_misc_idle_status_8_1);

PPATUI_HEADERIFY(mc_hub_misc_override_6_0);

PPATUI_HEADERIFY(mc_hub_misc_power_6_0);

PPATUI_HEADERIFY(mc_hub_misc_sip_cg_6_0);

PPATUI_HEADERIFY(mc_hub_misc_status_6_0);
PPATUI_HEADERIFY(mc_hub_misc_status_8_1);

PPATUI_HEADERIFY(mc_hub_misc_vm_cg_6_0);

PPATUI_HEADERIFY(mc_hub_perfcounter0_cfg_7_0);

PPATUI_HEADERIFY(mc_hub_perfcounter1_cfg_7_0);

PPATUI_HEADERIFY(mc_hub_perfcounter2_cfg_7_0);

PPATUI_HEADERIFY(mc_hub_perfcounter3_cfg_7_0);

PPATUI_HEADERIFY(mc_hub_perfcounter_hi_7_0);

PPATUI_HEADERIFY(mc_hub_perfcounter_lo_7_0);

PPATUI_HEADERIFY(mc_hub_perfcounter_rslt_cntl_7_0);

PPATUI_HEADERIFY(mc_hub_rdreq_acpg_7_0);

PPATUI_HEADERIFY(mc_hub_rdreq_acpg_limit_7_0);

PPATUI_HEADERIFY(mc_hub_rdreq_acpo_7_0);

PPATUI_HEADERIFY(mc_hub_rdreq_bypass_gbl0_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_cntl_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_cntl_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_cntl_7_1);
PPATUI_HEADERIFY(mc_hub_rdreq_cntl_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_cpc_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_cpc_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_cpf_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_cpf_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_cpg_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_cpg_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_credits_6_0);

PPATUI_HEADERIFY(mc_hub_rdreq_credits2_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_credits2_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_dmif_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_dmif_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_dmif_limit_6_0);

PPATUI_HEADERIFY(mc_hub_rdreq_gbl0_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_gbl0_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_gbl1_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_gbl1_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_hdp_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_hdp_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_ia_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_ia_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_ia0_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_ia0_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_ia1_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_ia1_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_isp_ccpu_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_isp_mpm_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_isp_spm_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_mcds_8_1);
PPATUI_HEADERIFY(mc_hub_rdreq_mcds_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_mcdt_8_1);
PPATUI_HEADERIFY(mc_hub_rdreq_mcdt_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_mcdu_8_1);
PPATUI_HEADERIFY(mc_hub_rdreq_mcdu_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_mcdv_8_1);
PPATUI_HEADERIFY(mc_hub_rdreq_mcdv_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_mcdw_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_mcdw_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_mcdx_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_mcdx_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_mcdy_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_mcdy_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_mcdz_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_mcdz_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_mcif_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_mcif_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_rlc_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_rlc_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_sam_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_sam_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_sammsp_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_sdma0_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_sdma0_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_sdma1_7_0);
PPATUI_HEADERIFY(mc_hub_rdreq_sdma1_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_sem_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_sem_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_sip_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_sip_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_smu_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_smu_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_status_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_status_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_tls_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_umc_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_umc_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_uvd_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_uvd_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_vce_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_vce_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_vce0_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_vce1_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_vceu_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_vceu_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_vceu0_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_vceu1_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_vmc_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_vmc_7_1);

PPATUI_HEADERIFY(mc_hub_rdreq_vp8_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_vp8u_8_1);

PPATUI_HEADERIFY(mc_hub_rdreq_wtm_cntl_6_0);

PPATUI_HEADERIFY(mc_hub_rdreq_xdmam_6_0);
PPATUI_HEADERIFY(mc_hub_rdreq_xdmam_7_1);

PPATUI_HEADERIFY(mc_hub_shared_dagb_dly_6_0);
PPATUI_HEADERIFY(mc_hub_shared_dagb_dly_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_acpg_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_acpg_7_0);

PPATUI_HEADERIFY(mc_hub_wdp_acpo_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_acpo_7_0);

PPATUI_HEADERIFY(mc_hub_wdp_bp_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_bp2_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_bypass_gbl0_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_bypass_gbl1_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_cntl_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_cntl_7_1);
PPATUI_HEADERIFY(mc_hub_wdp_cntl_8_1);

PPATUI_HEADERIFY(mc_hub_wdp_cpc_7_0);
PPATUI_HEADERIFY(mc_hub_wdp_cpc_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_cpf_7_0);
PPATUI_HEADERIFY(mc_hub_wdp_cpf_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_cpg_7_0);
PPATUI_HEADERIFY(mc_hub_wdp_cpg_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_credits_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_credits2_7_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits2_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits2_8_2);

PPATUI_HEADERIFY(mc_hub_wdp_credits3_8_1);

PPATUI_HEADERIFY(mc_hub_wdp_credits_mcds_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits_mcds_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdt_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdt_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdu_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdu_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdv_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdv_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdw_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdw_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdx_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdx_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdy_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdy_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdz_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_credits_mcdz_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_err_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_gbl0_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_gbl0_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_gbl0_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_gbl1_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_gbl1_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_gbl1_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_hdp_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_hdp_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_hdp_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_ih_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_ih_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_ih_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_isp_ccpu_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_isp_ccpu_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_isp_mpm_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_isp_mpm_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_isp_mps_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_isp_mps_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_isp_spm_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_isp_spm_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_mcds_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_mcdt_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_mcdu_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_mcdv_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_mcdw_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_mcdx_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_mcdy_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_mcdz_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_mcif_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_mcif_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_mcif_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_mgpu_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_mgpu2_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_rlc_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_rlc_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_rlc_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_sam_7_0);
PPATUI_HEADERIFY(mc_hub_wdp_sam_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_sammsp_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_sammsp_8_2);

PPATUI_HEADERIFY(mc_hub_wdp_sdma0_7_0);
PPATUI_HEADERIFY(mc_hub_wdp_sdma0_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_sdma0_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_sdma1_7_0);
PPATUI_HEADERIFY(mc_hub_wdp_sdma1_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_sdma1_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_sem_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_sem_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_sem_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_sh0_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_sh0_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_sh0_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_sh1_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_sh1_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_sh1_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_sh2_7_0);
PPATUI_HEADERIFY(mc_hub_wdp_sh2_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_sh2_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_sh3_7_0);
PPATUI_HEADERIFY(mc_hub_wdp_sh3_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_sh3_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_sip_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_smu_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_smu_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_smu_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_status_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_status_7_0);
PPATUI_HEADERIFY(mc_hub_wdp_status_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_umc_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_umc_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_umc_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_uvd_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_uvd_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_uvd_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_vce_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_vce_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_vce0_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_vce0_8_2);

PPATUI_HEADERIFY(mc_hub_wdp_vce1_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_vce1_8_2);

PPATUI_HEADERIFY(mc_hub_wdp_vceu_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_vceu_7_1);

PPATUI_HEADERIFY(mc_hub_wdp_vceu0_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_vceu0_8_2);

PPATUI_HEADERIFY(mc_hub_wdp_vceu1_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_vceu1_8_2);

PPATUI_HEADERIFY(mc_hub_wdp_vin0_8_1);

PPATUI_HEADERIFY(mc_hub_wdp_vp8_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_vp8_8_2);

PPATUI_HEADERIFY(mc_hub_wdp_vp8u_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_vp8u_8_2);

PPATUI_HEADERIFY(mc_hub_wdp_wtm_cntl_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_xdma_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_xdma_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_xdmam_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_xdmam_6_0);

PPATUI_HEADERIFY(mc_hub_wdp_xdp_6_0);
PPATUI_HEADERIFY(mc_hub_wdp_xdp_8_1);
PPATUI_HEADERIFY(mc_hub_wdp_xdp_7_1);

PPATUI_HEADERIFY(mc_hub_wrret_cntl_6_0);

PPATUI_HEADERIFY(mc_hub_wrret_mcds_7_1);

PPATUI_HEADERIFY(mc_hub_wrret_mcdt_7_1);

PPATUI_HEADERIFY(mc_hub_wrret_mcdu_7_1);

PPATUI_HEADERIFY(mc_hub_wrret_mcdv_7_1);

PPATUI_HEADERIFY(mc_hub_wrret_mcdw_6_0);

PPATUI_HEADERIFY(mc_hub_wrret_mcdx_6_0);

PPATUI_HEADERIFY(mc_hub_wrret_mcdy_6_0);

PPATUI_HEADERIFY(mc_hub_wrret_mcdz_6_0);

PPATUI_HEADERIFY(mc_hub_wrret_status_6_0);
PPATUI_HEADERIFY(mc_hub_wrret_status_7_1);

PPATUI_HEADERIFY(mc_imp_cntl_6_0);

PPATUI_HEADERIFY(mc_imp_debug_6_0);

PPATUI_HEADERIFY(mc_imp_dq_status_6_0);

PPATUI_HEADERIFY(mc_imp_status_6_0);

PPATUI_HEADERIFY(mc_io_aphy_str_cntl_d0_6_0);

PPATUI_HEADERIFY(mc_io_aphy_str_cntl_d1_6_0);

PPATUI_HEADERIFY(mc_io_cdrcntl1_d0_6_0);

PPATUI_HEADERIFY(mc_io_cdrcntl1_d1_6_0);

PPATUI_HEADERIFY(mc_io_cdrcntl2_d0_6_0);
PPATUI_HEADERIFY(mc_io_cdrcntl2_d0_7_1);

PPATUI_HEADERIFY(mc_io_cdrcntl2_d1_6_0);
PPATUI_HEADERIFY(mc_io_cdrcntl2_d1_7_1);

PPATUI_HEADERIFY(mc_io_cdrcntl_d0_6_0);

PPATUI_HEADERIFY(mc_io_cdrcntl_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_acmd_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrh_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_addrl_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_ck_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_cmd_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_cdr_phsize_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_cdr_phsize_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dbi_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dq0_rx_dyn_pm_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dq0_rx_dyn_pm_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dq0_rx_eq_pm_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dq0_rx_eq_pm_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dq1_rx_dyn_pm_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dq1_rx_dyn_pm_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dq1_rx_eq_pm_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dq1_rx_eq_pm_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0_cdr_phsize_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0_cdr_phsize_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0h_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb0l_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1_cdr_phsize_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1_cdr_phsize_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1h_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb1l_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2_cdr_phsize_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2_cdr_phsize_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2h_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb2l_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3_cdr_phsize_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3_cdr_phsize_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3h_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_dqb3l_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_cdr_phsize_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_cdr_phsize_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rx_dyn_pm_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rx_dyn_pm_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rx_eq_pm_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rx_eq_pm_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_edc_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_0_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_1_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_10_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_100_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_101_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_102_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_103_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_104_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_105_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_106_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_107_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_108_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_109_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_11_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_110_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_111_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_112_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_113_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_114_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_115_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_116_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_117_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_118_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_119_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_12_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_120_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_121_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_122_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_123_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_124_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_125_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_126_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_127_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_128_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_129_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_13_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_130_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_131_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_132_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_133_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_134_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_135_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_136_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_137_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_138_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_139_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_14_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_140_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_141_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_142_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_143_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_144_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_145_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_146_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_147_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_148_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_149_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_15_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_150_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_151_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_152_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_153_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_154_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_155_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_156_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_157_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_158_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_159_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_16_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_17_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_18_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_19_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_2_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_20_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_21_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_22_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_23_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_24_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_25_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_26_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_27_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_28_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_29_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_3_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_30_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_31_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_32_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_33_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_34_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_35_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_36_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_37_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_38_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_39_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_4_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_40_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_41_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_42_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_43_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_44_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_45_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_46_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_47_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_48_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_49_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_5_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_50_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_51_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_52_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_53_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_54_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_55_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_56_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_57_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_58_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_59_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_6_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_60_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_61_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_62_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_63_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_64_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_65_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_66_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_67_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_68_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_69_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_7_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_70_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_71_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_72_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_73_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_74_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_75_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_76_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_77_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_78_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_79_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_8_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_80_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_81_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_82_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_83_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_84_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_85_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_86_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_87_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_88_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_89_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_9_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_90_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_91_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_92_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_93_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_94_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_95_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_96_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_97_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_98_6_0);

PPATUI_HEADERIFY(mc_io_debug_up_99_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_cdr_phsize_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_cdr_phsize_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rx_dyn_pm_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rx_dyn_pm_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rx_eq_pm_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rx_eq_pm_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wcdr_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_clksel_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_clksel_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_misc_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_misc_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_ofscal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_ofscal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_rx_eq_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_rx_eq_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_rx_vref_cal_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_rx_vref_cal_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_rxphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_rxphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_txbst_pd_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_txbst_pd_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_txbst_pu_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_txbst_pu_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_txphase_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_txphase_d1_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_txslf_d0_6_0);

PPATUI_HEADERIFY(mc_io_debug_wck_txslf_d1_6_0);

PPATUI_HEADERIFY(mc_io_dphy_str_cntl_d0_6_0);
PPATUI_HEADERIFY(mc_io_dphy_str_cntl_d0_7_1);

PPATUI_HEADERIFY(mc_io_dphy_str_cntl_d1_6_0);
PPATUI_HEADERIFY(mc_io_dphy_str_cntl_d1_7_1);

PPATUI_HEADERIFY(mc_io_pad_cntl_6_0);

PPATUI_HEADERIFY(mc_io_pad_cntl_d0_6_0);

PPATUI_HEADERIFY(mc_io_pad_cntl_d1_6_0);

PPATUI_HEADERIFY(mc_io_rxcntl1_dphy0_d0_6_0);
PPATUI_HEADERIFY(mc_io_rxcntl1_dphy0_d0_7_1);

PPATUI_HEADERIFY(mc_io_rxcntl1_dphy0_d1_6_0);
PPATUI_HEADERIFY(mc_io_rxcntl1_dphy0_d1_7_1);

PPATUI_HEADERIFY(mc_io_rxcntl1_dphy1_d0_6_0);
PPATUI_HEADERIFY(mc_io_rxcntl1_dphy1_d0_7_1);

PPATUI_HEADERIFY(mc_io_rxcntl1_dphy1_d1_6_0);
PPATUI_HEADERIFY(mc_io_rxcntl1_dphy1_d1_7_1);

PPATUI_HEADERIFY(mc_io_rxcntl_dphy0_d0_6_0);

PPATUI_HEADERIFY(mc_io_rxcntl_dphy0_d1_6_0);

PPATUI_HEADERIFY(mc_io_rxcntl_dphy1_d0_6_0);

PPATUI_HEADERIFY(mc_io_rxcntl_dphy1_d1_6_0);

PPATUI_HEADERIFY(mc_io_txcntl_aphy_d0_6_0);

PPATUI_HEADERIFY(mc_io_txcntl_aphy_d1_6_0);

PPATUI_HEADERIFY(mc_io_txcntl_dphy0_d0_6_0);

PPATUI_HEADERIFY(mc_io_txcntl_dphy0_d1_6_0);

PPATUI_HEADERIFY(mc_io_txcntl_dphy1_d0_6_0);

PPATUI_HEADERIFY(mc_io_txcntl_dphy1_d1_6_0);

PPATUI_HEADERIFY(mc_mcbvm_perfcounter0_cfg_7_0);

PPATUI_HEADERIFY(mc_mcbvm_perfcounter1_cfg_7_0);

PPATUI_HEADERIFY(mc_mcbvm_perfcounter2_cfg_7_0);

PPATUI_HEADERIFY(mc_mcbvm_perfcounter3_cfg_7_0);

PPATUI_HEADERIFY(mc_mcbvm_perfcounter_hi_7_0);

PPATUI_HEADERIFY(mc_mcbvm_perfcounter_lo_7_0);

PPATUI_HEADERIFY(mc_mcbvm_perfcounter_rslt_cntl_7_0);

PPATUI_HEADERIFY(mc_mcdvm_perfcounter0_cfg_7_0);

PPATUI_HEADERIFY(mc_mcdvm_perfcounter1_cfg_7_0);

PPATUI_HEADERIFY(mc_mcdvm_perfcounter2_cfg_7_0);

PPATUI_HEADERIFY(mc_mcdvm_perfcounter3_cfg_7_0);

PPATUI_HEADERIFY(mc_mcdvm_perfcounter_hi_7_0);

PPATUI_HEADERIFY(mc_mcdvm_perfcounter_lo_7_0);

PPATUI_HEADERIFY(mc_mcdvm_perfcounter_rslt_cntl_7_0);

PPATUI_HEADERIFY(mc_mem_power_ls_6_0);

PPATUI_HEADERIFY(mc_npl_status_6_0);

PPATUI_HEADERIFY(mc_phy_timing_2_6_0);
PPATUI_HEADERIFY(mc_phy_timing_2_7_1);

PPATUI_HEADERIFY(mc_phy_timing_d0_6_0);

PPATUI_HEADERIFY(mc_phy_timing_d1_6_0);

PPATUI_HEADERIFY(mc_pmg_auto_cfg_6_0);

PPATUI_HEADERIFY(mc_pmg_auto_cmd_6_0);

PPATUI_HEADERIFY(mc_pmg_cfg_6_0);

PPATUI_HEADERIFY(mc_pmg_cmd_emrs_6_0);

PPATUI_HEADERIFY(mc_pmg_cmd_mrs_6_0);

PPATUI_HEADERIFY(mc_pmg_cmd_mrs1_6_0);

PPATUI_HEADERIFY(mc_pmg_cmd_mrs2_6_0);

PPATUI_HEADERIFY(mc_rd_cb_6_0);

PPATUI_HEADERIFY(mc_rd_db_6_0);

PPATUI_HEADERIFY(mc_rd_grp_ext_6_0);

PPATUI_HEADERIFY(mc_rd_grp_gfx_6_0);
PPATUI_HEADERIFY(mc_rd_grp_gfx_7_0);
PPATUI_HEADERIFY(mc_rd_grp_gfx_7_1);
PPATUI_HEADERIFY(mc_rd_grp_gfx_8_1);
PPATUI_HEADERIFY(mc_rd_grp_gfx_8_2);

PPATUI_HEADERIFY(mc_rd_grp_lcl_6_0);

PPATUI_HEADERIFY(mc_rd_grp_oth_6_0);
PPATUI_HEADERIFY(mc_rd_grp_oth_7_0);
PPATUI_HEADERIFY(mc_rd_grp_oth_8_1);

PPATUI_HEADERIFY(mc_rd_grp_sys_6_0);
PPATUI_HEADERIFY(mc_rd_grp_sys_7_0);
PPATUI_HEADERIFY(mc_rd_grp_sys_8_1);

PPATUI_HEADERIFY(mc_rd_hub_6_0);

PPATUI_HEADERIFY(mc_rd_tc0_6_0);

PPATUI_HEADERIFY(mc_rd_tc1_6_0);

PPATUI_HEADERIFY(mc_rpb_arb_cntl_6_0);

PPATUI_HEADERIFY(mc_rpb_bif_cntl_6_0);

PPATUI_HEADERIFY(mc_rpb_cid_queue_ex_6_0);

PPATUI_HEADERIFY(mc_rpb_cid_queue_ex_data_6_0);

PPATUI_HEADERIFY(mc_rpb_cid_queue_rd_6_0);

PPATUI_HEADERIFY(mc_rpb_cid_queue_wr_6_0);

PPATUI_HEADERIFY(mc_rpb_conf_6_0);

PPATUI_HEADERIFY(mc_rpb_dbg1_6_0);

PPATUI_HEADERIFY(mc_rpb_eff_cntl_6_0);

PPATUI_HEADERIFY(mc_rpb_if_conf_6_0);

PPATUI_HEADERIFY(mc_rpb_perf_counter_cntl_6_0);

PPATUI_HEADERIFY(mc_rpb_perf_counter_status_6_0);

PPATUI_HEADERIFY(mc_rpb_perfcounter0_cfg_7_0);

PPATUI_HEADERIFY(mc_rpb_perfcounter1_cfg_7_0);

PPATUI_HEADERIFY(mc_rpb_perfcounter2_cfg_7_0);

PPATUI_HEADERIFY(mc_rpb_perfcounter3_cfg_7_0);

PPATUI_HEADERIFY(mc_rpb_perfcounter_hi_7_0);

PPATUI_HEADERIFY(mc_rpb_perfcounter_lo_7_0);

PPATUI_HEADERIFY(mc_rpb_perfcounter_rslt_cntl_7_0);

PPATUI_HEADERIFY(mc_rpb_rd_switch_cntl_6_0);

PPATUI_HEADERIFY(mc_rpb_tci_cntl_7_1);

PPATUI_HEADERIFY(mc_rpb_tci_cntl2_8_1);

PPATUI_HEADERIFY(mc_rpb_wr_combine_cntl_6_0);

PPATUI_HEADERIFY(mc_rpb_wr_switch_cntl_6_0);

PPATUI_HEADERIFY(mc_seq_bit_remap_b0_d0_6_0);

PPATUI_HEADERIFY(mc_seq_bit_remap_b0_d1_6_0);

PPATUI_HEADERIFY(mc_seq_bit_remap_b1_d0_6_0);

PPATUI_HEADERIFY(mc_seq_bit_remap_b1_d1_6_0);

PPATUI_HEADERIFY(mc_seq_bit_remap_b2_d0_6_0);

PPATUI_HEADERIFY(mc_seq_bit_remap_b2_d1_6_0);

PPATUI_HEADERIFY(mc_seq_bit_remap_b3_d0_6_0);

PPATUI_HEADERIFY(mc_seq_bit_remap_b3_d1_6_0);

PPATUI_HEADERIFY(mc_seq_byte_remap_d0_6_0);

PPATUI_HEADERIFY(mc_seq_byte_remap_d1_6_0);

PPATUI_HEADERIFY(mc_seq_cas_timing_6_0);

PPATUI_HEADERIFY(mc_seq_cas_timing_lp_6_0);

PPATUI_HEADERIFY(mc_seq_cg_6_0);

PPATUI_HEADERIFY(mc_seq_cmd_6_0);

PPATUI_HEADERIFY(mc_seq_cntl_6_0);

PPATUI_HEADERIFY(mc_seq_cntl_2_6_0);
PPATUI_HEADERIFY(mc_seq_cntl_2_7_1);

PPATUI_HEADERIFY(mc_seq_cntl_3_7_1);

PPATUI_HEADERIFY(mc_seq_dll_stby_7_1);

PPATUI_HEADERIFY(mc_seq_dll_stby_lp_7_1);

PPATUI_HEADERIFY(mc_seq_dram_6_0);
PPATUI_HEADERIFY(mc_seq_dram_7_1);

PPATUI_HEADERIFY(mc_seq_dram_2_6_0);

PPATUI_HEADERIFY(mc_seq_dram_error_insertion_6_0);

PPATUI_HEADERIFY(mc_seq_fifo_ctl_6_0);
PPATUI_HEADERIFY(mc_seq_fifo_ctl_7_1);

PPATUI_HEADERIFY(mc_seq_g5pdx_cmd0_7_1);

PPATUI_HEADERIFY(mc_seq_g5pdx_cmd0_lp_7_1);

PPATUI_HEADERIFY(mc_seq_g5pdx_cmd1_7_1);

PPATUI_HEADERIFY(mc_seq_g5pdx_cmd1_lp_7_1);

PPATUI_HEADERIFY(mc_seq_g5pdx_ctrl_7_1);

PPATUI_HEADERIFY(mc_seq_g5pdx_ctrl_lp_7_1);

PPATUI_HEADERIFY(mc_seq_io_debug_data_6_0);

PPATUI_HEADERIFY(mc_seq_io_debug_index_6_0);

PPATUI_HEADERIFY(mc_seq_io_rdbi_6_0);

PPATUI_HEADERIFY(mc_seq_io_redc_6_0);

PPATUI_HEADERIFY(mc_seq_io_reserve_d0_6_0);

PPATUI_HEADERIFY(mc_seq_io_reserve_d1_6_0);

PPATUI_HEADERIFY(mc_seq_io_rword0_6_0);

PPATUI_HEADERIFY(mc_seq_io_rword1_6_0);

PPATUI_HEADERIFY(mc_seq_io_rword2_6_0);

PPATUI_HEADERIFY(mc_seq_io_rword3_6_0);

PPATUI_HEADERIFY(mc_seq_io_rword4_6_0);

PPATUI_HEADERIFY(mc_seq_io_rword5_6_0);

PPATUI_HEADERIFY(mc_seq_io_rword6_6_0);

PPATUI_HEADERIFY(mc_seq_io_rword7_6_0);

PPATUI_HEADERIFY(mc_seq_misc0_6_0);

PPATUI_HEADERIFY(mc_seq_misc1_6_0);

PPATUI_HEADERIFY(mc_seq_misc3_6_0);

PPATUI_HEADERIFY(mc_seq_misc4_6_0);

PPATUI_HEADERIFY(mc_seq_misc5_6_0);

PPATUI_HEADERIFY(mc_seq_misc6_6_0);

PPATUI_HEADERIFY(mc_seq_misc7_6_0);

PPATUI_HEADERIFY(mc_seq_misc8_6_0);

PPATUI_HEADERIFY(mc_seq_misc9_6_0);

PPATUI_HEADERIFY(mc_seq_misc_timing_6_0);

PPATUI_HEADERIFY(mc_seq_misc_timing2_6_0);

PPATUI_HEADERIFY(mc_seq_misc_timing2_lp_6_0);

PPATUI_HEADERIFY(mc_seq_misc_timing_lp_6_0);

PPATUI_HEADERIFY(mc_seq_mpll_override_6_0);

PPATUI_HEADERIFY(mc_seq_perf_cntl_6_0);

PPATUI_HEADERIFY(mc_seq_perf_cntl_1_6_0);

PPATUI_HEADERIFY(mc_seq_perf_seq_cnt_a_i0_6_0);

PPATUI_HEADERIFY(mc_seq_perf_seq_cnt_a_i1_6_0);

PPATUI_HEADERIFY(mc_seq_perf_seq_cnt_b_i0_6_0);

PPATUI_HEADERIFY(mc_seq_perf_seq_cnt_b_i1_6_0);

PPATUI_HEADERIFY(mc_seq_perf_seq_cnt_c_i0_6_0);

PPATUI_HEADERIFY(mc_seq_perf_seq_cnt_c_i1_6_0);

PPATUI_HEADERIFY(mc_seq_perf_seq_cnt_d_i0_6_0);

PPATUI_HEADERIFY(mc_seq_perf_seq_cnt_d_i1_6_0);

PPATUI_HEADERIFY(mc_seq_perf_seq_ctl_6_0);

PPATUI_HEADERIFY(mc_seq_phyreg_bcast_7_1);

PPATUI_HEADERIFY(mc_seq_pmg_cmd_emrs_lp_6_0);

PPATUI_HEADERIFY(mc_seq_pmg_cmd_mrs1_lp_6_0);

PPATUI_HEADERIFY(mc_seq_pmg_cmd_mrs2_lp_6_0);

PPATUI_HEADERIFY(mc_seq_pmg_cmd_mrs_lp_6_0);

PPATUI_HEADERIFY(mc_seq_pmg_dvs_cmd_7_1);

PPATUI_HEADERIFY(mc_seq_pmg_dvs_cmd_lp_7_1);

PPATUI_HEADERIFY(mc_seq_pmg_dvs_ctl_7_1);

PPATUI_HEADERIFY(mc_seq_pmg_dvs_ctl_lp_7_1);

PPATUI_HEADERIFY(mc_seq_pmg_pg_hwcntl_6_0);

PPATUI_HEADERIFY(mc_seq_pmg_pg_swcntl_0_6_0);

PPATUI_HEADERIFY(mc_seq_pmg_pg_swcntl_1_6_0);

PPATUI_HEADERIFY(mc_seq_pmg_timing_6_0);

PPATUI_HEADERIFY(mc_seq_pmg_timing_lp_6_0);

PPATUI_HEADERIFY(mc_seq_ras_timing_6_0);

PPATUI_HEADERIFY(mc_seq_ras_timing_lp_6_0);

PPATUI_HEADERIFY(mc_seq_rd_ctl_d0_6_0);

PPATUI_HEADERIFY(mc_seq_rd_ctl_d0_lp_6_0);

PPATUI_HEADERIFY(mc_seq_rd_ctl_d1_6_0);

PPATUI_HEADERIFY(mc_seq_rd_ctl_d1_lp_6_0);

PPATUI_HEADERIFY(mc_seq_reserve_0_s_7_1);
PPATUI_HEADERIFY(mc_seq_reserve_0_s_6_0);

PPATUI_HEADERIFY(mc_seq_reserve_1_s_6_0);

PPATUI_HEADERIFY(mc_seq_reserve_m_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_byte0_d0_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_byte0_d1_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_byte1_d0_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_byte1_d1_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_byte2_d0_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_byte2_d1_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_byte3_d0_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_byte3_d1_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_dbi_d0_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_dbi_d1_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_edc_d0_6_0);

PPATUI_HEADERIFY(mc_seq_rxframing_edc_d1_6_0);

PPATUI_HEADERIFY(mc_seq_sreg_read_7_1);

PPATUI_HEADERIFY(mc_seq_sreg_status_7_1);

PPATUI_HEADERIFY(mc_seq_status_m_6_0);
PPATUI_HEADERIFY(mc_seq_status_m_7_1);

PPATUI_HEADERIFY(mc_seq_status_s_6_0);

PPATUI_HEADERIFY(mc_seq_sup_cntl_6_0);

PPATUI_HEADERIFY(mc_seq_sup_dec_stat_6_0);

PPATUI_HEADERIFY(mc_seq_sup_gp0_stat_6_0);

PPATUI_HEADERIFY(mc_seq_sup_gp1_stat_6_0);

PPATUI_HEADERIFY(mc_seq_sup_gp2_stat_6_0);

PPATUI_HEADERIFY(mc_seq_sup_gp3_stat_6_0);

PPATUI_HEADERIFY(mc_seq_sup_ir_stat_6_0);

PPATUI_HEADERIFY(mc_seq_sup_pgm_6_0);

PPATUI_HEADERIFY(mc_seq_sup_pgm_stat_6_0);

PPATUI_HEADERIFY(mc_seq_sup_r_pgm_6_0);

PPATUI_HEADERIFY(mc_seq_tcg_cntl_6_0);
PPATUI_HEADERIFY(mc_seq_tcg_cntl_7_1);

PPATUI_HEADERIFY(mc_seq_timer_rd_6_0);

PPATUI_HEADERIFY(mc_seq_timer_wr_6_0);

PPATUI_HEADERIFY(mc_seq_train_capture_6_0);
PPATUI_HEADERIFY(mc_seq_train_capture_7_1);

PPATUI_HEADERIFY(mc_seq_train_edc_threshold_6_0);

PPATUI_HEADERIFY(mc_seq_train_edc_threshold2_6_0);

PPATUI_HEADERIFY(mc_seq_train_edc_threshold3_6_0);

PPATUI_HEADERIFY(mc_seq_train_timing_6_0);

PPATUI_HEADERIFY(mc_seq_train_wakeup_clear_6_0);
PPATUI_HEADERIFY(mc_seq_train_wakeup_clear_7_1);

PPATUI_HEADERIFY(mc_seq_train_wakeup_cntl_6_0);

PPATUI_HEADERIFY(mc_seq_train_wakeup_edge_6_0);
PPATUI_HEADERIFY(mc_seq_train_wakeup_edge_7_1);

PPATUI_HEADERIFY(mc_seq_train_wakeup_mask_6_0);
PPATUI_HEADERIFY(mc_seq_train_wakeup_mask_7_1);

PPATUI_HEADERIFY(mc_seq_tsm_bcnt_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_ctrl_6_0);
PPATUI_HEADERIFY(mc_seq_tsm_ctrl_7_1);

PPATUI_HEADERIFY(mc_seq_tsm_dbi_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_debug_data_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_debug_index_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_edc_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_flag_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_gcnt_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_misc_6_0);
PPATUI_HEADERIFY(mc_seq_tsm_misc_7_1);

PPATUI_HEADERIFY(mc_seq_tsm_ncnt_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_ocnt_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_update_6_0);

PPATUI_HEADERIFY(mc_seq_tsm_wcdr_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_byte0_d0_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_byte0_d1_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_byte1_d0_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_byte1_d1_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_byte2_d0_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_byte2_d1_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_byte3_d0_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_byte3_d1_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_dbi_d0_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_dbi_d1_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_edc_d0_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_edc_d1_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_fck_d0_6_0);

PPATUI_HEADERIFY(mc_seq_txframing_fck_d1_6_0);

PPATUI_HEADERIFY(mc_seq_vendor_id_i0_6_0);

PPATUI_HEADERIFY(mc_seq_vendor_id_i1_6_0);

PPATUI_HEADERIFY(mc_seq_wcdr_ctrl_6_0);

PPATUI_HEADERIFY(mc_seq_wr_ctl_2_6_0);

PPATUI_HEADERIFY(mc_seq_wr_ctl_2_lp_6_0);

PPATUI_HEADERIFY(mc_seq_wr_ctl_d0_6_0);

PPATUI_HEADERIFY(mc_seq_wr_ctl_d0_lp_6_0);

PPATUI_HEADERIFY(mc_seq_wr_ctl_d1_6_0);

PPATUI_HEADERIFY(mc_seq_wr_ctl_d1_lp_6_0);

PPATUI_HEADERIFY(mc_shared_active_fcn_id_8_1);

PPATUI_HEADERIFY(mc_shared_blackout_cntl_6_0);
PPATUI_HEADERIFY(mc_shared_blackout_cntl_8_1);

PPATUI_HEADERIFY(mc_shared_chmap_6_0);
PPATUI_HEADERIFY(mc_shared_chmap_7_1);

PPATUI_HEADERIFY(mc_shared_chremap_6_0);
PPATUI_HEADERIFY(mc_shared_chremap_7_1);

PPATUI_HEADERIFY(mc_shared_chremap2_7_1);

PPATUI_HEADERIFY(mc_shared_vf_enable_8_1);

PPATUI_HEADERIFY(mc_shared_virt_reset_req_8_1);

PPATUI_HEADERIFY(mc_train_edc_status_d0_6_0);

PPATUI_HEADERIFY(mc_train_edc_status_d1_6_0);

PPATUI_HEADERIFY(mc_train_edccdr_r_d0_6_0);

PPATUI_HEADERIFY(mc_train_edccdr_r_d1_6_0);

PPATUI_HEADERIFY(mc_train_prbserr_0_d0_6_0);

PPATUI_HEADERIFY(mc_train_prbserr_0_d1_6_0);

PPATUI_HEADERIFY(mc_train_prbserr_1_d0_6_0);

PPATUI_HEADERIFY(mc_train_prbserr_1_d1_6_0);

PPATUI_HEADERIFY(mc_train_prbserr_2_d0_6_0);

PPATUI_HEADERIFY(mc_train_prbserr_2_d1_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt0_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt1_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt10_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt2_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt3_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt4_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt5_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt6_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt7_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt8_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bcnt9_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_bkpt_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_flag_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_gcnt_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_misc_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_st01_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_st23_6_0);

PPATUI_HEADERIFY(mc_tsm_debug_st45_6_0);

PPATUI_HEADERIFY(mc_vm_agp_base_6_0);

PPATUI_HEADERIFY(mc_vm_agp_bot_6_0);

PPATUI_HEADERIFY(mc_vm_agp_top_6_0);

PPATUI_HEADERIFY(mc_vm_dc_write_cntl_6_0);

PPATUI_HEADERIFY(mc_vm_dc_write_hit_region_0_high_addr_6_0);

PPATUI_HEADERIFY(mc_vm_dc_write_hit_region_0_low_addr_6_0);

PPATUI_HEADERIFY(mc_vm_dc_write_hit_region_1_high_addr_6_0);

PPATUI_HEADERIFY(mc_vm_dc_write_hit_region_1_low_addr_6_0);

PPATUI_HEADERIFY(mc_vm_dc_write_hit_region_2_high_addr_6_0);

PPATUI_HEADERIFY(mc_vm_dc_write_hit_region_2_low_addr_6_0);

PPATUI_HEADERIFY(mc_vm_dc_write_hit_region_3_high_addr_6_0);

PPATUI_HEADERIFY(mc_vm_dc_write_hit_region_3_low_addr_6_0);

PPATUI_HEADERIFY(mc_vm_fb_location_6_0);

PPATUI_HEADERIFY(mc_vm_fb_offset_6_0);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf0_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf1_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf10_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf11_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf12_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf13_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf14_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf15_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf2_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf3_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf4_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf5_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf6_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf7_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf8_8_1);

PPATUI_HEADERIFY(mc_vm_fb_size_offset_vf9_8_1);

PPATUI_HEADERIFY(mc_vm_l2_perfcounter0_cfg_7_0);

PPATUI_HEADERIFY(mc_vm_l2_perfcounter1_cfg_7_0);

PPATUI_HEADERIFY(mc_vm_l2_perfcounter_hi_7_0);

PPATUI_HEADERIFY(mc_vm_l2_perfcounter_lo_7_0);

PPATUI_HEADERIFY(mc_vm_l2_perfcounter_rslt_cntl_7_0);

PPATUI_HEADERIFY(mc_vm_marc_base_hi_0_8_1);

PPATUI_HEADERIFY(mc_vm_marc_base_hi_1_8_1);

PPATUI_HEADERIFY(mc_vm_marc_base_hi_2_8_1);

PPATUI_HEADERIFY(mc_vm_marc_base_hi_3_8_1);

PPATUI_HEADERIFY(mc_vm_marc_base_lo_0_8_1);

PPATUI_HEADERIFY(mc_vm_marc_base_lo_1_8_1);

PPATUI_HEADERIFY(mc_vm_marc_base_lo_2_8_1);

PPATUI_HEADERIFY(mc_vm_marc_base_lo_3_8_1);

PPATUI_HEADERIFY(mc_vm_marc_cntl_8_1);

PPATUI_HEADERIFY(mc_vm_marc_len_hi_0_8_1);

PPATUI_HEADERIFY(mc_vm_marc_len_hi_1_8_1);

PPATUI_HEADERIFY(mc_vm_marc_len_hi_2_8_1);

PPATUI_HEADERIFY(mc_vm_marc_len_hi_3_8_1);

PPATUI_HEADERIFY(mc_vm_marc_len_lo_0_8_1);

PPATUI_HEADERIFY(mc_vm_marc_len_lo_1_8_1);

PPATUI_HEADERIFY(mc_vm_marc_len_lo_2_8_1);

PPATUI_HEADERIFY(mc_vm_marc_len_lo_3_8_1);

PPATUI_HEADERIFY(mc_vm_marc_reloc_hi_0_8_1);

PPATUI_HEADERIFY(mc_vm_marc_reloc_hi_1_8_1);

PPATUI_HEADERIFY(mc_vm_marc_reloc_hi_2_8_1);

PPATUI_HEADERIFY(mc_vm_marc_reloc_hi_3_8_1);

PPATUI_HEADERIFY(mc_vm_marc_reloc_lo_0_8_1);

PPATUI_HEADERIFY(mc_vm_marc_reloc_lo_1_8_1);

PPATUI_HEADERIFY(mc_vm_marc_reloc_lo_2_8_1);

PPATUI_HEADERIFY(mc_vm_marc_reloc_lo_3_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tlb0_debug_6_0);
PPATUI_HEADERIFY(mc_vm_mb_l1_tlb0_debug_7_0);

PPATUI_HEADERIFY(mc_vm_mb_l1_tlb0_status_6_0);

PPATUI_HEADERIFY(mc_vm_mb_l1_tlb1_debug_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tlb1_status_6_0);

PPATUI_HEADERIFY(mc_vm_mb_l1_tlb2_debug_6_0);
PPATUI_HEADERIFY(mc_vm_mb_l1_tlb2_debug_7_0);

PPATUI_HEADERIFY(mc_vm_mb_l1_tlb2_status_6_0);

PPATUI_HEADERIFY(mc_vm_mb_l1_tlb3_debug_6_0);
PPATUI_HEADERIFY(mc_vm_mb_l1_tlb3_debug_7_0);

PPATUI_HEADERIFY(mc_vm_mb_l1_tlb3_status_6_0);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_cntl0_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_cntl1_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_cntl2_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_cntl3_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_cntl4_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_cntl5_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_cntl6_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_cntl7_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_cntl8_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_end_addr0_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_end_addr1_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_end_addr2_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_end_addr3_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_end_addr4_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_end_addr5_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_end_addr6_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_end_addr7_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_end_addr8_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_protection_fault_addr_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_protection_fault_status_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_start_addr0_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_start_addr1_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_start_addr2_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_start_addr3_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_start_addr4_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_start_addr5_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_start_addr6_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_start_addr7_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l1_tls0_start_addr8_8_1);

PPATUI_HEADERIFY(mc_vm_mb_l2arbiter_l2_credits_6_0);

PPATUI_HEADERIFY(mc_vm_md_l1_tlb0_debug_6_0);
PPATUI_HEADERIFY(mc_vm_md_l1_tlb0_debug_7_0);

PPATUI_HEADERIFY(mc_vm_md_l1_tlb0_status_6_0);

PPATUI_HEADERIFY(mc_vm_md_l1_tlb1_debug_6_0);
PPATUI_HEADERIFY(mc_vm_md_l1_tlb1_debug_7_0);

PPATUI_HEADERIFY(mc_vm_md_l1_tlb1_status_6_0);

PPATUI_HEADERIFY(mc_vm_md_l1_tlb2_debug_6_0);
PPATUI_HEADERIFY(mc_vm_md_l1_tlb2_debug_7_0);

PPATUI_HEADERIFY(mc_vm_md_l1_tlb2_status_6_0);

PPATUI_HEADERIFY(mc_vm_md_l1_tlb3_debug_6_0);
PPATUI_HEADERIFY(mc_vm_md_l1_tlb3_debug_7_0);

PPATUI_HEADERIFY(mc_vm_md_l1_tlb3_status_6_0);

PPATUI_HEADERIFY(mc_vm_md_l2arbiter_l2_credits_6_0);

PPATUI_HEADERIFY(mc_vm_mx_l1_tlb_cntl_6_0);

PPATUI_HEADERIFY(mc_vm_nb_lower_top_of_dram2_8_1);

PPATUI_HEADERIFY(mc_vm_nb_mmiobase_8_1);

PPATUI_HEADERIFY(mc_vm_nb_mmiolimit_8_1);

PPATUI_HEADERIFY(mc_vm_nb_pci_arb_8_1);

PPATUI_HEADERIFY(mc_vm_nb_pci_ctrl_8_1);

PPATUI_HEADERIFY(mc_vm_nb_top_of_dram3_8_1);

PPATUI_HEADERIFY(mc_vm_nb_top_of_dram_slot1_8_1);

PPATUI_HEADERIFY(mc_vm_nb_upper_top_of_dram2_8_1);

PPATUI_HEADERIFY(mc_vm_steering_7_0);

PPATUI_HEADERIFY(mc_vm_system_aperture_default_addr_6_0);

PPATUI_HEADERIFY(mc_vm_system_aperture_high_addr_6_0);

PPATUI_HEADERIFY(mc_vm_system_aperture_low_addr_6_0);

PPATUI_HEADERIFY(mc_wr_cb_6_0);

PPATUI_HEADERIFY(mc_wr_db_6_0);

PPATUI_HEADERIFY(mc_wr_grp_ext_6_0);

PPATUI_HEADERIFY(mc_wr_grp_gfx_6_0);
PPATUI_HEADERIFY(mc_wr_grp_gfx_7_0);
PPATUI_HEADERIFY(mc_wr_grp_gfx_7_1);
PPATUI_HEADERIFY(mc_wr_grp_gfx_8_1);
PPATUI_HEADERIFY(mc_wr_grp_gfx_8_2);

PPATUI_HEADERIFY(mc_wr_grp_lcl_6_0);

PPATUI_HEADERIFY(mc_wr_grp_oth_6_0);
PPATUI_HEADERIFY(mc_wr_grp_oth_7_0);

PPATUI_HEADERIFY(mc_wr_grp_sys_6_0);
PPATUI_HEADERIFY(mc_wr_grp_sys_7_0);
PPATUI_HEADERIFY(mc_wr_grp_sys_8_1);

PPATUI_HEADERIFY(mc_wr_hub_6_0);

PPATUI_HEADERIFY(mc_wr_tc0_6_0);

PPATUI_HEADERIFY(mc_wr_tc1_6_0);

PPATUI_HEADERIFY(mc_xbar_addr_dec_6_0);

PPATUI_HEADERIFY(mc_xbar_arb_6_0);
PPATUI_HEADERIFY(mc_xbar_arb_8_1);
PPATUI_HEADERIFY(mc_xbar_arb_8_2);

PPATUI_HEADERIFY(mc_xbar_arb_max_burst_6_0);

PPATUI_HEADERIFY(mc_xbar_chtriremap_6_0);

PPATUI_HEADERIFY(mc_xbar_fifo_mon_cntl0_8_1);

PPATUI_HEADERIFY(mc_xbar_fifo_mon_cntl1_8_1);

PPATUI_HEADERIFY(mc_xbar_fifo_mon_cntl2_8_1);

PPATUI_HEADERIFY(mc_xbar_fifo_mon_max_thsh_8_1);

PPATUI_HEADERIFY(mc_xbar_fifo_mon_rslt0_8_1);

PPATUI_HEADERIFY(mc_xbar_fifo_mon_rslt1_8_1);

PPATUI_HEADERIFY(mc_xbar_fifo_mon_rslt2_8_1);

PPATUI_HEADERIFY(mc_xbar_fifo_mon_rslt3_8_1);

PPATUI_HEADERIFY(mc_xbar_perf_mon_cntl0_6_0);

PPATUI_HEADERIFY(mc_xbar_perf_mon_cntl1_6_0);

PPATUI_HEADERIFY(mc_xbar_perf_mon_cntl2_6_0);

PPATUI_HEADERIFY(mc_xbar_perf_mon_max_thsh_6_0);

PPATUI_HEADERIFY(mc_xbar_perf_mon_rslt0_6_0);

PPATUI_HEADERIFY(mc_xbar_perf_mon_rslt1_6_0);

PPATUI_HEADERIFY(mc_xbar_perf_mon_rslt2_6_0);

PPATUI_HEADERIFY(mc_xbar_perf_mon_rslt3_6_0);

PPATUI_HEADERIFY(mc_xbar_rdreq_credit_6_0);

PPATUI_HEADERIFY(mc_xbar_rdreq_pri_credit_6_0);

PPATUI_HEADERIFY(mc_xbar_rdret_credit1_6_0);

PPATUI_HEADERIFY(mc_xbar_rdret_credit2_6_0);

PPATUI_HEADERIFY(mc_xbar_rdret_pri_credit1_6_0);

PPATUI_HEADERIFY(mc_xbar_rdret_pri_credit2_6_0);

PPATUI_HEADERIFY(mc_xbar_remote_6_0);

PPATUI_HEADERIFY(mc_xbar_spare0_6_0);

PPATUI_HEADERIFY(mc_xbar_spare1_6_0);

PPATUI_HEADERIFY(mc_xbar_twochan_6_0);

PPATUI_HEADERIFY(mc_xbar_wrreq_credit_6_0);

PPATUI_HEADERIFY(mc_xbar_wrret_credit1_6_0);

PPATUI_HEADERIFY(mc_xbar_wrret_credit2_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg0_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg1_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg10_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg11_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg12_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg13_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg14_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg15_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg16_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg17_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg18_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg19_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg2_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg20_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg21_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg22_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg23_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg24_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg25_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg26_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg27_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg28_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg29_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg3_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg30_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg31_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg32_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg33_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg34_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg35_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg36_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg4_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg5_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg6_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg7_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg8_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_cfg9_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_extra_6_0);

PPATUI_HEADERIFY(mc_xpb_clg_extra_rd_6_0);

PPATUI_HEADERIFY(mc_xpb_clk_gat_6_0);

PPATUI_HEADERIFY(mc_xpb_intf_cfg_6_0);

PPATUI_HEADERIFY(mc_xpb_intf_cfg2_6_0);

PPATUI_HEADERIFY(mc_xpb_intf_sts_6_0);

PPATUI_HEADERIFY(mc_xpb_lb_addr_6_0);

PPATUI_HEADERIFY(mc_xpb_map_invert_flush_num_lsb_6_0);

PPATUI_HEADERIFY(mc_xpb_misc_cfg_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar0_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar1_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar2_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar3_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar4_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar5_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar6_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar7_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar_cfg_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar_debug_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar_delta_above_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar_delta_below_6_0);

PPATUI_HEADERIFY(mc_xpb_p2p_bar_setup_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar0_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar1_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar2_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar3_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar4_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar5_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar6_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar7_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar8_6_0);

PPATUI_HEADERIFY(mc_xpb_peer_sys_bar9_6_0);

PPATUI_HEADERIFY(mc_xpb_perf_knobs_6_0);

PPATUI_HEADERIFY(mc_xpb_pipe_sts_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map0_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map1_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map2_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map3_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map4_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map5_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map6_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map7_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map8_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_dest_map9_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr0_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr1_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr2_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr3_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr4_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr5_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr6_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr7_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr8_6_0);

PPATUI_HEADERIFY(mc_xpb_rtr_src_aprtr9_6_0);

PPATUI_HEADERIFY(mc_xpb_sticky_6_0);

PPATUI_HEADERIFY(mc_xpb_sticky_w1c_6_0);

PPATUI_HEADERIFY(mc_xpb_sub_ctrl_6_0);

PPATUI_HEADERIFY(mc_xpb_unc_thresh_hst_6_0);

PPATUI_HEADERIFY(mc_xpb_unc_thresh_sid_6_0);

PPATUI_HEADERIFY(mc_xpb_wcb_cfg_6_0);

PPATUI_HEADERIFY(mc_xpb_wcb_sts_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_peer_sys_bar0_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_peer_sys_bar1_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_peer_sys_bar2_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_peer_sys_bar3_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_rtr_dest_map0_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_rtr_dest_map1_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_rtr_dest_map2_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_rtr_dest_map3_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_rtr_src_aprtr0_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_rtr_src_aprtr1_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_rtr_src_aprtr2_6_0);

PPATUI_HEADERIFY(mc_xpb_xdma_rtr_src_aprtr3_6_0);

PPATUI_HEADERIFY(mcif_wb_arbitration_control_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_1_addr_c_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_1_addr_c_offset_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_1_addr_y_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_1_addr_y_offset_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_1_status_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_1_status2_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_2_addr_c_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_2_addr_c_offset_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_2_addr_y_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_2_addr_y_offset_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_2_status_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_2_status2_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_3_addr_c_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_3_addr_c_offset_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_3_addr_y_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_3_addr_y_offset_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_3_status_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_3_status2_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_4_addr_c_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_4_addr_c_offset_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_4_addr_y_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_4_addr_y_offset_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_4_status_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_4_status2_8_1);

PPATUI_HEADERIFY(mcif_wb_buf_pitch_8_1);

PPATUI_HEADERIFY(mcif_wb_bufmgr_cur_line_r_8_1);

PPATUI_HEADERIFY(mcif_wb_bufmgr_status_8_1);

PPATUI_HEADERIFY(mcif_wb_bufmgr_sw_control_8_1);

PPATUI_HEADERIFY(mcif_wb_bufmgr_vce_control_8_1);

PPATUI_HEADERIFY(mcif_wb_hvvmid_control_8_1);

PPATUI_HEADERIFY(mcif_wb_test_debug_data_8_1);

PPATUI_HEADERIFY(mcif_wb_test_debug_index_8_1);

PPATUI_HEADERIFY(mcif_wb_urgency_watermark_8_1);

PPATUI_HEADERIFY(mclk_pwrmgt_cntl_6_0);

PPATUI_HEADERIFY(mpll_ad_func_cntl_6_0);

PPATUI_HEADERIFY(mpll_ad_status_6_0);

PPATUI_HEADERIFY(mpll_cntl_mode_6_0);
PPATUI_HEADERIFY(mpll_cntl_mode_8_1);

PPATUI_HEADERIFY(mpll_control_6_0);

PPATUI_HEADERIFY(mpll_dq_0_0_status_6_0);

PPATUI_HEADERIFY(mpll_dq_0_1_status_6_0);

PPATUI_HEADERIFY(mpll_dq_1_0_status_6_0);

PPATUI_HEADERIFY(mpll_dq_1_1_status_6_0);

PPATUI_HEADERIFY(mpll_dq_func_cntl_6_0);

PPATUI_HEADERIFY(mpll_func_cntl_6_0);

PPATUI_HEADERIFY(mpll_func_cntl_1_6_0);

PPATUI_HEADERIFY(mpll_func_cntl_2_6_0);
PPATUI_HEADERIFY(mpll_func_cntl_2_7_1);

PPATUI_HEADERIFY(mpll_seq_ucode_1_6_0);

PPATUI_HEADERIFY(mpll_seq_ucode_2_6_0);

PPATUI_HEADERIFY(mpll_ss1_6_0);

PPATUI_HEADERIFY(mpll_ss2_6_0);

PPATUI_HEADERIFY(mpll_time_6_0);

PPATUI_HEADERIFY(vm_context0_cntl_6_0);
PPATUI_HEADERIFY(vm_context0_cntl_8_1);

PPATUI_HEADERIFY(vm_context0_cntl2_6_0);

PPATUI_HEADERIFY(vm_context0_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context0_page_table_end_addr_6_0);

PPATUI_HEADERIFY(vm_context0_page_table_start_addr_6_0);

PPATUI_HEADERIFY(vm_context0_protection_fault_addr_6_0);

PPATUI_HEADERIFY(vm_context0_protection_fault_default_addr_6_0);

PPATUI_HEADERIFY(vm_context0_protection_fault_mcclient_7_0);

PPATUI_HEADERIFY(vm_context0_protection_fault_status_6_0);
PPATUI_HEADERIFY(vm_context0_protection_fault_status_7_1);
PPATUI_HEADERIFY(vm_context0_protection_fault_status_8_1);

PPATUI_HEADERIFY(vm_context10_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context11_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context12_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context13_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context14_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context15_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context1_cntl_6_0);
PPATUI_HEADERIFY(vm_context1_cntl_8_1);

PPATUI_HEADERIFY(vm_context1_cntl2_6_0);

PPATUI_HEADERIFY(vm_context1_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context1_page_table_end_addr_6_0);

PPATUI_HEADERIFY(vm_context1_page_table_start_addr_6_0);

PPATUI_HEADERIFY(vm_context1_protection_fault_addr_6_0);

PPATUI_HEADERIFY(vm_context1_protection_fault_default_addr_6_0);

PPATUI_HEADERIFY(vm_context1_protection_fault_mcclient_7_0);

PPATUI_HEADERIFY(vm_context1_protection_fault_status_6_0);
PPATUI_HEADERIFY(vm_context1_protection_fault_status_7_1);
PPATUI_HEADERIFY(vm_context1_protection_fault_status_8_1);

PPATUI_HEADERIFY(vm_context2_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context3_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context4_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context5_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context6_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context7_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context8_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_context9_page_table_base_addr_6_0);

PPATUI_HEADERIFY(vm_contexts_disable_6_0);

PPATUI_HEADERIFY(vm_debug_6_0);

PPATUI_HEADERIFY(vm_dummy_page_fault_addr_6_0);

PPATUI_HEADERIFY(vm_dummy_page_fault_cntl_6_0);

PPATUI_HEADERIFY(vm_fault_client_id_6_0);
PPATUI_HEADERIFY(vm_fault_client_id_8_1);

PPATUI_HEADERIFY(vm_invalidate_request_6_0);

PPATUI_HEADERIFY(vm_invalidate_response_6_0);

PPATUI_HEADERIFY(vm_l2_bank_select_maska_6_0);

PPATUI_HEADERIFY(vm_l2_bank_select_maskb_7_1);
PPATUI_HEADERIFY(vm_l2_bank_select_maskb_6_0);
PPATUI_HEADERIFY(vm_l2_bank_select_maskb_8_2);

PPATUI_HEADERIFY(vm_l2_bank_select_reserved_cid_8_1);

PPATUI_HEADERIFY(vm_l2_bank_select_reserved_cid2_8_1);

PPATUI_HEADERIFY(vm_l2_cg_6_0);
PPATUI_HEADERIFY(vm_l2_cg_8_1);

PPATUI_HEADERIFY(vm_l2_cntl_6_0);
PPATUI_HEADERIFY(vm_l2_cntl_7_0);

PPATUI_HEADERIFY(vm_l2_cntl2_6_0);
PPATUI_HEADERIFY(vm_l2_cntl2_7_0);

PPATUI_HEADERIFY(vm_l2_cntl3_6_0);
PPATUI_HEADERIFY(vm_l2_cntl3_8_1);
PPATUI_HEADERIFY(vm_l2_cntl3_7_0);

PPATUI_HEADERIFY(vm_l2_cntl4_8_1);
PPATUI_HEADERIFY(vm_l2_cntl4_8_2);

PPATUI_HEADERIFY(vm_l2_context1_identity_aperture_high_addr_6_0);

PPATUI_HEADERIFY(vm_l2_context1_identity_aperture_low_addr_6_0);

PPATUI_HEADERIFY(vm_l2_context_identity_physical_offset_6_0);

PPATUI_HEADERIFY(vm_l2_status_6_0);

PPATUI_HEADERIFY(vm_prt_aperture0_high_addr_6_0);

PPATUI_HEADERIFY(vm_prt_aperture0_low_addr_6_0);

PPATUI_HEADERIFY(vm_prt_aperture1_high_addr_6_0);

PPATUI_HEADERIFY(vm_prt_aperture1_low_addr_6_0);

PPATUI_HEADERIFY(vm_prt_aperture2_high_addr_6_0);

PPATUI_HEADERIFY(vm_prt_aperture2_low_addr_6_0);

PPATUI_HEADERIFY(vm_prt_aperture3_high_addr_6_0);

PPATUI_HEADERIFY(vm_prt_aperture3_low_addr_6_0);

PPATUI_HEADERIFY(vm_prt_cntl_6_0);
PPATUI_HEADERIFY(vm_prt_cntl_7_0);

#endif
