/*
Header files inclded herein are autogenerated. See meson.build and ppatui.py
*/

#ifndef ATUI_INCLUDES_H
#define ATUI_INCLUDES_H

#include "atui_enums.h"

#include "atui_gmc.h"
#include "atui_atomfirmware.h"
#include "atui_smu_v13_pptable.h"
#include "atui_smu_v11_pptable.h"
#include "atui_ddrmoderegisters.h"
#include "atui_atombios.h"
#include "atui_powerplay.h"
#include "atui_umctimings.h"

#endif
