/*
autogenerated with asic_reg.py - manually trimmed
Considers DCN versions: 1_0, 2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
*/

#ifndef DCN_H
#define DCN_H
#pragma pack(push, 1) // bios data must use byte alignment

#define mmDC_GPIO_AUX_CTRL_0_1_0 0x2916 //1_0
#define mmDC_GPIO_AUX_CTRL_0_BASE_IDX_1_0 2 //1_0
union dc_gpio_aux_ctrl_0_1_0 { //1_0
	uint32_t raw_data;
	struct { uint32_t
		dc_gpio_aux1_fallslewsel    :1-0 +1,
		dc_gpio_aux2_fallslewsel    :3-2 +1,
		dc_gpio_aux3_fallslewsel    :5-4 +1,
		dc_gpio_aux4_fallslewsel    :7-6 +1,
		dc_gpio_aux5_fallslewsel    :9-8 +1,
		dc_gpio_aux6_fallslewsel   :11-10 +1,
		dc_gpio_ddcvga_fallslewsel :13-12 +1,
		dc_gpio_geni2c_fallslewsel :15-14 +1,
		dc_gpio_aux1_spikercen     :16-16 +1,
		dc_gpio_aux2_spikercen     :17-17 +1,
		dc_gpio_aux3_spikercen     :18-18 +1,
		dc_gpio_aux4_spikercen     :19-19 +1,
		dc_gpio_aux5_spikercen     :20-20 +1,
		dc_gpio_aux6_spikercen     :21-21 +1,
		dc_gpio_ddcvga_spikercen   :22-22 +1,
		dc_gpio_geni2c_spikercen   :23-23 +1,
		dc_gpio_aux1_spikercsel    :24-24 +1,
		dc_gpio_aux2_spikercsel    :25-25 +1,
		dc_gpio_aux3_spikercsel    :26-26 +1,
		dc_gpio_aux4_spikercsel    :27-27 +1,
		dc_gpio_aux5_spikercsel    :28-28 +1,
		dc_gpio_aux6_spikercsel    :29-29 +1,
		dc_gpio_ddcvga_spikercsel  :30-30 +1,
		dc_gpio_geni2c_spikercsel  :31-31 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_0_2_0_0 0x2916 //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6
#define regDC_GPIO_AUX_CTRL_0_BASE_IDX_2_0_0 2 //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6
union dc_gpio_aux_ctrl_0_2_0_0 { //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6
	uint32_t raw_data;
	struct { uint32_t
		dc_gpio_aux1_fallslewsel    :1-0 +1,
		dc_gpio_aux2_fallslewsel    :3-2 +1,
		dc_gpio_aux3_fallslewsel    :5-4 +1,
		dc_gpio_aux4_fallslewsel    :7-6 +1,
		dc_gpio_aux5_fallslewsel    :9-8 +1,
		dc_gpio_aux6_fallslewsel   :11-10 +1,
		dc_gpio_ddcvga_fallslewsel :13-12 +1,
		_rsvd00                    :15-14 +1,
		dc_gpio_aux1_spikercen     :16-16 +1,
		dc_gpio_aux2_spikercen     :17-17 +1,
		dc_gpio_aux3_spikercen     :18-18 +1,
		dc_gpio_aux4_spikercen     :19-19 +1,
		dc_gpio_aux5_spikercen     :20-20 +1,
		dc_gpio_aux6_spikercen     :21-21 +1,
		dc_gpio_ddcvga_spikercen   :22-22 +1,
		_rsvd01                    :23-23 +1,
		dc_gpio_aux1_spikercsel    :24-24 +1,
		dc_gpio_aux2_spikercsel    :25-25 +1,
		dc_gpio_aux3_spikercsel    :26-26 +1,
		dc_gpio_aux4_spikercsel    :27-27 +1,
		dc_gpio_aux5_spikercsel    :28-28 +1,
		dc_gpio_aux6_spikercsel    :29-29 +1,
		dc_gpio_ddcvga_spikercsel  :30-30 +1,
		_rsvd02                    :31-31 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_0_3_2_0 0x2916 //3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
#define regDC_GPIO_AUX_CTRL_0_BASE_IDX_3_2_0 2 //3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
union dc_gpio_aux_ctrl_0_3_2_0 { //3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
	uint32_t raw_data;
	struct { uint32_t
		dc_gpio_aux1_fallslewsel    :1-0 +1,
		dc_gpio_aux2_fallslewsel    :3-2 +1,
		dc_gpio_aux3_fallslewsel    :5-4 +1,
		dc_gpio_aux4_fallslewsel    :7-6 +1,
		dc_gpio_aux5_fallslewsel    :9-8 +1,
		dc_gpio_aux6_fallslewsel   :11-10 +1,
		dc_gpio_ddcvga_fallslewsel :13-12 +1,
		_rsvd00                    :15-14 +1,
		dc_gpio_aux1_spikercen     :16-16 +1,
		dc_gpio_aux2_spikercen     :17-17 +1,
		dc_gpio_aux3_spikercen     :18-18 +1,
		dc_gpio_aux4_spikercen     :19-19 +1,
		dc_gpio_aux5_spikercen     :20-20 +1,
		dc_gpio_aux6_spikercen     :21-21 +1,
		dc_gpio_ddcvga_spikercen   :23-22 +1,
		dc_gpio_aux1_spikercsel    :24-24 +1,
		dc_gpio_aux2_spikercsel    :25-25 +1,
		dc_gpio_aux3_spikercsel    :26-26 +1,
		dc_gpio_aux4_spikercsel    :27-27 +1,
		dc_gpio_aux5_spikercsel    :28-28 +1,
		dc_gpio_aux6_spikercsel    :29-29 +1,
		dc_gpio_ddcvga_spikercsel  :31-30 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_0_4_1_0 0x2916 //4_1_0
#define regDC_GPIO_AUX_CTRL_0_BASE_IDX_4_1_0 2 //4_1_0
union dc_gpio_aux_ctrl_0_4_1_0 { //4_1_0
	uint32_t raw_data;
	struct { uint32_t
		_rsvd00                    :11-0 +1,
		dc_gpio_ddcvga_fallslewsel :13-12 +1,
		_rsvd01                    :21-14 +1,
		dc_gpio_ddcvga_spikercen   :23-22 +1,
		_rsvd02                    :29-24 +1,
		dc_gpio_ddcvga_spikercsel  :31-30 +1;
	};
};


#define mmDC_GPIO_AUX_CTRL_1_1_0 0x2917 //1_0
#define mmDC_GPIO_AUX_CTRL_1_BASE_IDX_1_0 2 //1_0
union dc_gpio_aux_ctrl_1_1_0 { //1_0
	uint32_t raw_data;
	struct { uint32_t
		dc_gpio_aux_csel_0p9    :0-0 +1,
		dc_gpio_aux_csel_1p1    :1-1 +1,
		dc_gpio_aux_rsel_0p9    :2-2 +1,
		dc_gpio_aux_rsel_1p1    :3-3 +1,
		dc_gpio_i2c_csel_0p9    :4-4 +1,
		dc_gpio_i2c_csel_1p1    :5-5 +1,
		dc_gpio_i2c_rsel_0p9    :6-6 +1,
		dc_gpio_i2c_rsel_1p1    :7-7 +1,
		dc_gpio_aux_biascrten   :8-8 +1,
		dc_gpio_i2c_biascrten   :9-9 +1,
		dc_gpio_aux_resbiasen  :10-10 +1,
		dc_gpio_i2c_resbiasen  :11-11 +1,
		dc_gpio_aux1_compsel   :12-12 +1,
		dc_gpio_geni2c_compsel :13-13 +1,
		dc_gpio_ddcvga_spare   :15-14 +1,
		dc_gpio_geni2c_spare   :17-16 +1,
		dc_gpio_ddcvga_slewn   :18-18 +1,
		dc_gpio_geni2c_slewn   :19-19 +1,
		dc_gpio_ddcvga_rxsel   :21-20 +1,
		dc_gpio_geni2c_rxsel   :23-22 +1,
		dc_gpio_geni2c_pden    :24-24 +1,
		dc_gpio_aux2_compsel   :25-25 +1,
		dc_gpio_aux3_compsel   :26-26 +1,
		dc_gpio_aux4_compsel   :27-27 +1,
		dc_gpio_aux5_compsel   :28-28 +1,
		dc_gpio_aux6_compsel   :29-29 +1,
		dc_gpio_ddcvga_compsel :30-30 +1,
		_rsvd00                :31-31 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_1_2_0_0 0x2917 //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6
#define regDC_GPIO_AUX_CTRL_1_BASE_IDX_2_0_0 2 //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6
union dc_gpio_aux_ctrl_1_2_0_0 { //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6
	uint32_t raw_data;
	struct { uint32_t
		dc_gpio_aux_csel_0p9    :0-0 +1,
		dc_gpio_aux_csel_1p1    :1-1 +1,
		dc_gpio_aux_rsel_0p9    :2-2 +1,
		dc_gpio_aux_rsel_1p1    :3-3 +1,
		dc_gpio_i2c_csel_0p9    :4-4 +1,
		dc_gpio_i2c_csel_1p1    :5-5 +1,
		dc_gpio_i2c_rsel_0p9    :6-6 +1,
		dc_gpio_i2c_rsel_1p1    :7-7 +1,
		dc_gpio_aux_biascrten   :8-8 +1,
		dc_gpio_i2c_biascrten   :9-9 +1,
		dc_gpio_aux_resbiasen  :10-10 +1,
		dc_gpio_i2c_resbiasen  :11-11 +1,
		dc_gpio_aux1_compsel   :12-12 +1,
		_rsvd00                :13-13 +1,
		dc_gpio_ddcvga_spare   :15-14 +1,
		_rsvd01                :17-16 +1,
		dc_gpio_ddcvga_slewn   :18-18 +1,
		_rsvd02                :19-19 +1,
		dc_gpio_ddcvga_rxsel   :21-20 +1,
		_rsvd03                :24-22 +1,
		dc_gpio_aux2_compsel   :25-25 +1,
		dc_gpio_aux3_compsel   :26-26 +1,
		dc_gpio_aux4_compsel   :27-27 +1,
		dc_gpio_aux5_compsel   :28-28 +1,
		dc_gpio_aux6_compsel   :29-29 +1,
		dc_gpio_ddcvga_compsel :30-30 +1,
		_rsvd04                :31-31 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_1_3_2_0 0x2917 //3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
#define regDC_GPIO_AUX_CTRL_1_BASE_IDX_3_2_0 2 //3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
union dc_gpio_aux_ctrl_1_3_2_0 { //3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
	uint32_t raw_data;
	struct { uint32_t
		dc_gpio_aux_csel_0p9    :0-0 +1,
		dc_gpio_aux_csel_1p1    :1-1 +1,
		dc_gpio_aux_rsel_0p9    :2-2 +1,
		dc_gpio_aux_rsel_1p1    :3-3 +1,
		dc_gpio_i2c_csel_0p9    :4-4 +1,
		dc_gpio_i2c_csel_1p1    :5-5 +1,
		dc_gpio_i2c_rsel_0p9    :6-6 +1,
		dc_gpio_i2c_rsel_1p1    :7-7 +1,
		dc_gpio_aux_biascrten   :8-8 +1,
		_rsvd00                 :9-9 +1,
		dc_gpio_aux_resbiasen  :10-10 +1,
		dc_gpio_i2c_resbiasen  :12-11 +1,
		dc_gpio_aux1_compsel   :13-13 +1,
		dc_gpio_ddcvga_spare   :15-14 +1,
		dc_gpio_i2c_biascrten  :17-16 +1,
		dc_gpio_ddcvga_slewn   :19-18 +1,
		dc_gpio_ddcvga_rxsel   :21-20 +1,
		_rsvd01                :24-22 +1,
		dc_gpio_aux2_compsel   :25-25 +1,
		dc_gpio_aux3_compsel   :26-26 +1,
		dc_gpio_aux4_compsel   :27-27 +1,
		dc_gpio_aux5_compsel   :28-28 +1,
		dc_gpio_aux6_compsel   :29-29 +1,
		dc_gpio_ddcvga_compsel :31-30 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_1_4_1_0 0x2917 //4_1_0
#define regDC_GPIO_AUX_CTRL_1_BASE_IDX_4_1_0 2 //4_1_0
union dc_gpio_aux_ctrl_1_4_1_0 { //4_1_0
	uint32_t raw_data;
	struct { uint32_t
		_rsvd00                 :3-0 +1,
		dc_gpio_i2c_csel_0p9    :4-4 +1,
		dc_gpio_i2c_csel_1p1    :5-5 +1,
		dc_gpio_i2c_rsel_0p9    :6-6 +1,
		dc_gpio_i2c_rsel_1p1    :7-7 +1,
		_rsvd01                :10-8 +1,
		dc_gpio_i2c_resbiasen  :12-11 +1,
		dc_gpio_aux1_compsel   :13-13 +1,
		dc_gpio_ddcvga_spare   :15-14 +1,
		dc_gpio_i2c_biascrten  :17-16 +1,
		dc_gpio_ddcvga_slewn   :19-18 +1,
		dc_gpio_ddcvga_rxsel   :21-20 +1,
		_rsvd02                :24-22 +1,
		dc_gpio_aux2_compsel   :25-25 +1,
		dc_gpio_aux3_compsel   :26-26 +1,
		dc_gpio_aux4_compsel   :27-27 +1,
		dc_gpio_aux5_compsel   :28-28 +1,
		dc_gpio_aux6_compsel   :29-29 +1,
		dc_gpio_ddcvga_compsel :31-30 +1;
	};
};


#define mmDC_GPIO_AUX_CTRL_2_2_0_1 0x2918 //2_0_1
#define mmDC_GPIO_AUX_CTRL_2_BASE_IDX_2_0_1 2 //2_0_1
union dc_gpio_aux_ctrl_2_2_0_1 { //2_0_1
	uint32_t raw_data;
	struct { uint32_t
		dc_gpio_hpd12_fallslewsel :1-0 +1,
		_rsvd00                   :7-2 +1,
		dc_gpio_hpd12_spikercen   :8-8 +1,
		_rsvd01                  :11-9 +1,
		dc_gpio_hpd12_spikercsel :12-12 +1,
		_rsvd02                  :15-13 +1,
		dc_gpio_hpd_csel_0p9     :16-16 +1,
		dc_gpio_hpd_csel_1p1     :17-17 +1,
		dc_gpio_hpd_rsel_0p9     :18-18 +1,
		dc_gpio_hpd_rsel_1p1     :19-19 +1,
		dc_gpio_hpd_biascrten    :20-20 +1,
		_rsvd03                  :23-21 +1,
		dc_gpio_hpd12_slewn      :24-24 +1,
		_rsvd04                  :26-25 +1,
		dc_gpio_hpd_resbiasen    :27-27 +1,
		dc_gpio_hpd12_compsel    :28-28 +1,
		_rsvd05                  :31-29 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_2_1_0 0x2918 //1_0, 2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
#define regDC_GPIO_AUX_CTRL_2_BASE_IDX_1_0 2 //1_0, 2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
union dc_gpio_aux_ctrl_2_1_0 { //1_0, 2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
	uint32_t raw_data;
	struct { uint32_t
		dc_gpio_hpd12_fallslewsel :1-0 +1,
		dc_gpio_hpd34_fallslewsel :3-2 +1,
		dc_gpio_hpd56_fallslewsel :5-4 +1,
		_rsvd00                   :7-6 +1,
		dc_gpio_hpd12_spikercen   :8-8 +1,
		dc_gpio_hpd34_spikercen   :9-9 +1,
		dc_gpio_hpd56_spikercen  :10-10 +1,
		_rsvd01                  :11-11 +1,
		dc_gpio_hpd12_spikercsel :12-12 +1,
		dc_gpio_hpd34_spikercsel :13-13 +1,
		dc_gpio_hpd56_spikercsel :14-14 +1,
		_rsvd02                  :15-15 +1,
		dc_gpio_hpd_csel_0p9     :16-16 +1,
		dc_gpio_hpd_csel_1p1     :17-17 +1,
		dc_gpio_hpd_rsel_0p9     :18-18 +1,
		dc_gpio_hpd_rsel_1p1     :19-19 +1,
		dc_gpio_hpd_biascrten    :20-20 +1,
		_rsvd03                  :23-21 +1,
		dc_gpio_hpd12_slewn      :24-24 +1,
		dc_gpio_hpd34_slewn      :25-25 +1,
		dc_gpio_hpd56_slewn      :26-26 +1,
		dc_gpio_hpd_resbiasen    :27-27 +1,
		dc_gpio_hpd12_compsel    :28-28 +1,
		dc_gpio_hpd34_compsel    :29-29 +1,
		dc_gpio_hpd56_compsel    :30-30 +1,
		_rsvd04                  :31-31 +1;
	};
};


#define mmDC_GPIO_AUX_CTRL_3_2_0_1 0x291B //2_0_1
#define mmDC_GPIO_AUX_CTRL_3_BASE_IDX_2_0_1 2 //2_0_1
union dc_gpio_aux_ctrl_3_2_0_1 { //2_0_1
	uint32_t raw_data;
	struct { uint32_t
		aux1_nen_rterm  :0-0 +1,
		aux2_nen_rterm  :1-1 +1,
		_rsvd00         :7-2 +1,
		aux1_dp_dn_swap :8-8 +1,
		aux2_dp_dn_swap :9-9 +1,
		_rsvd01        :15-10 +1,
		aux1_hys_tune  :17-16 +1,
		aux2_hys_tune  :19-18 +1,
		_rsvd02        :31-20 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_3_2_0_0 0x291B //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
#define regDC_GPIO_AUX_CTRL_3_BASE_IDX_2_0_0 2 //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
union dc_gpio_aux_ctrl_3_2_0_0 { //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
	uint32_t raw_data;
	struct { uint32_t
		aux1_nen_rterm   :0-0 +1,
		aux2_nen_rterm   :1-1 +1,
		aux3_nen_rterm   :2-2 +1,
		aux4_nen_rterm   :3-3 +1,
		aux5_nen_rterm   :4-4 +1,
		aux6_nen_rterm   :5-5 +1,
		_rsvd00          :7-6 +1,
		aux1_dp_dn_swap  :8-8 +1,
		aux2_dp_dn_swap  :9-9 +1,
		aux3_dp_dn_swap :10-10 +1,
		aux4_dp_dn_swap :11-11 +1,
		aux5_dp_dn_swap :12-12 +1,
		aux6_dp_dn_swap :13-13 +1,
		_rsvd01         :15-14 +1,
		aux1_hys_tune   :17-16 +1,
		aux2_hys_tune   :19-18 +1,
		aux3_hys_tune   :21-20 +1,
		aux4_hys_tune   :23-22 +1,
		aux5_hys_tune   :25-24 +1,
		aux6_hys_tune   :27-26 +1,
		_rsvd02         :31-28 +1;
	};
};


#define mmDC_GPIO_AUX_CTRL_4_2_0_1 0x291C //2_0_1
#define mmDC_GPIO_AUX_CTRL_4_BASE_IDX_2_0_1 2 //2_0_1
union dc_gpio_aux_ctrl_4_2_0_1 { //2_0_1
	uint32_t raw_data;
	struct { uint32_t
		aux1_aux_ctrl :3-0 +1,
		aux2_aux_ctrl :7-4 +1,
		_rsvd00      :31-8 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_4_2_0_0 0x291C //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
#define regDC_GPIO_AUX_CTRL_4_BASE_IDX_2_0_0 2 //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
union dc_gpio_aux_ctrl_4_2_0_0 { //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
	uint32_t raw_data;
	struct { uint32_t
		aux1_aux_ctrl  :3-0 +1,
		aux2_aux_ctrl  :7-4 +1,
		aux3_aux_ctrl :11-8 +1,
		aux4_aux_ctrl :15-12 +1,
		aux5_aux_ctrl :19-16 +1,
		aux6_aux_ctrl :23-20 +1,
		_rsvd00       :31-24 +1;
	};
};


#define mmDC_GPIO_AUX_CTRL_5_2_0_1 0x291D //2_0_1
#define mmDC_GPIO_AUX_CTRL_5_BASE_IDX_2_0_1 2 //2_0_1
union dc_gpio_aux_ctrl_5_2_0_1 { //2_0_1
	uint32_t raw_data;
	struct { uint32_t
		aux1_vod_tune        :1-0 +1,
		aux2_vod_tune        :3-2 +1,
		_rsvd00             :11-4 +1,
		ddc_pad1_i2cmode    :12-12 +1,
		ddc_pad2_i2cmode    :13-13 +1,
		_rsvd01             :17-14 +1,
		ddc1_i2c_vph_1v2_en :18-18 +1,
		ddc2_i2c_vph_1v2_en :19-19 +1,
		_rsvd02             :23-20 +1,
		ddc1_pad_i2c_ctrl   :24-24 +1,
		ddc2_pad_i2c_ctrl   :25-25 +1,
		_rsvd03             :31-26 +1;
	};
};

#define regDC_GPIO_AUX_CTRL_5_2_0_0 0x291D //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
#define regDC_GPIO_AUX_CTRL_5_BASE_IDX_2_0_0 2 //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
union dc_gpio_aux_ctrl_5_2_0_0 { //2_0_0, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
	uint32_t raw_data;
	struct { uint32_t
		aux1_vod_tune        :1-0 +1,
		aux2_vod_tune        :3-2 +1,
		aux3_vod_tune        :5-4 +1,
		aux4_vod_tune        :7-6 +1,
		aux5_vod_tune        :9-8 +1,
		aux6_vod_tune       :11-10 +1,
		ddc_pad1_i2cmode    :12-12 +1,
		ddc_pad2_i2cmode    :13-13 +1,
		ddc_pad3_i2cmode    :14-14 +1,
		ddc_pad4_i2cmode    :15-15 +1,
		ddc_pad5_i2cmode    :16-16 +1,
		ddc_pad6_i2cmode    :17-17 +1,
		ddc1_i2c_vph_1v2_en :18-18 +1,
		ddc2_i2c_vph_1v2_en :19-19 +1,
		ddc3_i2c_vph_1v2_en :20-20 +1,
		ddc4_i2c_vph_1v2_en :21-21 +1,
		ddc5_i2c_vph_1v2_en :22-22 +1,
		ddc6_i2c_vph_1v2_en :23-23 +1,
		ddc1_pad_i2c_ctrl   :24-24 +1,
		ddc2_pad_i2c_ctrl   :25-25 +1,
		ddc3_pad_i2c_ctrl   :26-26 +1,
		ddc4_pad_i2c_ctrl   :27-27 +1,
		ddc5_pad_i2c_ctrl   :28-28 +1,
		ddc6_pad_i2c_ctrl   :29-29 +1,
		_rsvd00             :31-30 +1;
	};
};


#define mmDP_AUX0_AUX_DPHY_RX_CONTROL0_1_0 0x1F5A //1_0
#define mmDP_AUX0_AUX_DPHY_RX_CONTROL0_BASE_IDX_1_0 2 //1_0
union dp_aux0_aux_dphy_rx_control0_1_0 { //1_0
	uint32_t raw_data;
	struct { uint32_t
		_rsvd00                                    :3-0 +1,
		aux_rx_start_window                        :6-4 +1,
		_rsvd01                                    :7-7 +1,
		aux_rx_receive_window                     :10-8 +1,
		_rsvd02                                   :11-11 +1,
		aux_rx_half_sym_detect_len                :13-12 +1,
		_rsvd03                                   :15-14 +1,
		aux_rx_transition_filter_en               :16-16 +1,
		aux_rx_allow_below_threshold_phase_detect :17-17 +1,
		aux_rx_allow_below_threshold_start        :18-18 +1,
		aux_rx_allow_below_threshold_stop         :19-19 +1,
		aux_rx_phase_detect_len                   :21-20 +1,
		_rsvd04                                   :23-22 +1,
		aux_rx_timeout_len                        :26-24 +1,
		_rsvd05                                   :27-27 +1,
		aux_rx_detection_threshold                :30-28 +1,
		_rsvd06                                   :31-31 +1;
	};
};

#define regDP_AUX0_AUX_DPHY_RX_CONTROL0_2_0_0 0x1F5A //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
#define regDP_AUX0_AUX_DPHY_RX_CONTROL0_4_1_0 0x16BC //4_1_0
#define regDP_AUX0_AUX_DPHY_RX_CONTROL0_BASE_IDX_2_0_0 2 //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
union dp_aux0_aux_dphy_rx_control0_2_0_0 { //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
	uint32_t raw_data;
	struct { uint32_t
		_rsvd00                                    :3-0 +1,
		aux_rx_start_window                        :6-4 +1,
		_rsvd01                                    :7-7 +1,
		aux_rx_receive_window                     :10-8 +1,
		_rsvd02                                   :11-11 +1,
		aux_rx_half_sym_detect_len                :13-12 +1,
		_rsvd03                                   :15-14 +1,
		aux_rx_transition_filter_en               :16-16 +1,
		aux_rx_allow_below_threshold_phase_detect :17-17 +1,
		aux_rx_allow_below_threshold_start        :18-18 +1,
		aux_rx_allow_below_threshold_stop         :19-19 +1,
		aux_rx_phase_detect_len                   :21-20 +1,
		_rsvd04                                   :27-22 +1,
		aux_rx_detection_threshold                :30-28 +1,
		_rsvd05                                   :31-31 +1;
	};
};


#define mmDP_AUX0_AUX_DPHY_RX_CONTROL1_1_0 0x1F5B //1_0
#define mmDP_AUX0_AUX_DPHY_RX_CONTROL1_BASE_IDX_1_0 2 //1_0
union dp_aux0_aux_dphy_rx_control1_1_0 { //1_0
	uint32_t raw_data;
	struct { uint32_t
		aux_rx_precharge_skip :7-0 +1,
		_rsvd00              :31-8 +1;
	};
};

#define regDP_AUX0_AUX_DPHY_RX_CONTROL1_2_0_0 0x1F5B //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
#define regDP_AUX0_AUX_DPHY_RX_CONTROL1_4_1_0 0x16BD //4_1_0
#define regDP_AUX0_AUX_DPHY_RX_CONTROL1_BASE_IDX_2_0_0 2 //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
union dp_aux0_aux_dphy_rx_control1_2_0_0 { //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
	uint32_t raw_data;
	struct { uint32_t
		aux_rx_precharge_skip   :7-0 +1,
		aux_rx_timeout_len     :14-8 +1,
		aux_rx_timeout_len_mul :16-15 +1,
		_rsvd00                :31-17 +1;
	};
};


#define regDP_AUX0_AUX_DPHY_RX_STATUS_1_0 0x1F5D //1_0, 2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
#define regDP_AUX0_AUX_DPHY_RX_STATUS_4_1_0 0x16BF //4_1_0
#define regDP_AUX0_AUX_DPHY_RX_STATUS_BASE_IDX_1_0 2 //1_0, 2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
union dp_aux0_aux_dphy_rx_status_1_0 { //1_0, 2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
	uint32_t raw_data;
	struct { uint32_t
		aux_rx_state                  :2-0 +1,
		_rsvd00                       :7-3 +1,
		aux_rx_sync_valid_count      :12-8 +1,
		_rsvd01                      :15-13 +1,
		aux_rx_half_sym_period_fract :20-16 +1,
		aux_rx_half_sym_period       :29-21 +1,
		_rsvd02                      :31-30 +1;
	};
};


#define mmDP_AUX0_AUX_DPHY_TX_CONTROL_1_0 0x1F59 //1_0
#define mmDP_AUX0_AUX_DPHY_TX_CONTROL_BASE_IDX_1_0 2 //1_0
union dp_aux0_aux_dphy_tx_control_1_0 { //1_0
	uint32_t raw_data;
	struct { uint32_t
		aux_tx_precharge_len      :2-0 +1,
		_rsvd00                   :7-3 +1,
		aux_tx_precharge_symbols :13-8 +1,
		_rsvd01                  :15-14 +1,
		aux_mode_det_check_delay :18-16 +1,
		_rsvd02                  :31-19 +1;
	};
};

#define regDP_AUX0_AUX_DPHY_TX_CONTROL_2_0_0 0x1F59 //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0
#define regDP_AUX0_AUX_DPHY_TX_CONTROL_4_1_0 0x16BB //4_1_0
#define regDP_AUX0_AUX_DPHY_TX_CONTROL_BASE_IDX_2_0_0 2 //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
union dp_aux0_aux_dphy_tx_control_2_0_0 { //2_0_0, 2_0_1, 2_1_0, 3_0_0, 3_0_1, 3_0_2, 3_0_3, 3_1_2, 3_1_4, 3_1_5, 3_1_6, 3_2_0, 3_2_1, 3_5_0, 3_5_1, 3_6_0, 4_1_0
	uint32_t raw_data;
	struct { uint32_t
		aux_tx_precharge_len      :3-0 +1,
		aux_tx_precharge_len_mul  :5-4 +1,
		aux_tx_oe_assert_time     :6-6 +1,
		_rsvd00                   :7-7 +1,
		aux_tx_precharge_symbols :13-8 +1,
		_rsvd01                  :15-14 +1,
		aux_mode_det_check_delay :18-16 +1,
		_rsvd02                  :31-19 +1;
	};
};


#pragma pack(pop) // restore old packing
#endif
