/*
Header files included herein are autogenerated. See meson.build and ppatui.py
*/

#ifndef AUTO_INCLUDES_H
#define AUTO_INCLUDES_H

#include "atui_enums.h"

#include "atui_gc.h"
#include "atui_gmc.h"
#include "atui_atomfirmware.h"
#include "atui_smu_v13_pptable.h"
#include "atui_smu_v11_pptable.h"
#include "atui_ddrmoderegisters.h"
#include "atui_atombios.h"
#include "atui_powerplay.h"
#include "atui_asic_reg_data_tables.h"
#include "atui_bitfield_overrides.h"

#endif
