name: msys2_yaabe_release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag to build binaries for'
        required: true
        type: string
#  push:
#    tags:
#      v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: write

env:
  #YAABE_INSTALLER: yaabe-installer-${{github.ref_name}}.exe
  YAABE_INSTALLER: yaabe-installer-${{inputs.tag}}.exe


jobs:
  yaabe-windows-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            base-devel
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-python-json5
            mingw-w64-x86_64-nsis
      - name: yaabe_compile
        id: yaabe_compile
        run: |
          meson setup build --buildtype=release -Db_lto=true -Dnsis_installer=true
          cd build
          meson compile
      - name: sha_gen
        id: sha_gen
        run: |
		  cd ./build
          sha256sum $YAABE_INSTALLER
          sha256sum $YAABE_INSTALLER >> "$GITHUB_OUTPUT"
      - name: gh_page_release
        id: gh_page_release
        uses: softprops/action-gh-release@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          draft: true
          tag: refs/tags/${{inputs.tag}}
          body: ${{steps.sha_gen.outputs}}
          file: build/$YAABE_INSTALLER
